COMMENT ON TABLE sessions.vendor_session_projection_sync_targets IS 'Site-scoped HikCentral vendor session projection scheduler targets. This table configures refresh of continuity snapshots and is not parking-session authority, tariff authority, payment finality, or exit authorization.';
COMMENT ON COLUMN sessions.vendor_session_projection_sync_targets.projection_sync_target_id IS 'Canonical identifier of the projection sync target.';
COMMENT ON COLUMN sessions.vendor_session_projection_sync_targets.site_id IS 'ExitPass site scope for this projection sync target.';
COMMENT ON COLUMN sessions.vendor_session_projection_sync_targets.site_group_id IS 'ExitPass site group scope for this projection sync target.';
COMMENT ON COLUMN sessions.vendor_session_projection_sync_targets.vendor_system_id IS 'Vendor PMS that supplies passageway records for this target.';
COMMENT ON COLUMN sessions.vendor_session_projection_sync_targets.parking_lot_index_code IS 'HikCentral parking lot index code scoped to this target.';
COMMENT ON COLUMN sessions.vendor_session_projection_sync_targets.parking_lot_name IS 'Optional HikCentral parking lot display name.';
COMMENT ON COLUMN sessions.vendor_session_projection_sync_targets.enabled_flag IS 'Whether the centralized scheduler may run this target.';
COMMENT ON COLUMN sessions.vendor_session_projection_sync_targets.poll_interval_seconds IS 'Minimum interval between scheduled attempts for this target.';
COMMENT ON COLUMN sessions.vendor_session_projection_sync_targets.lookback_window_minutes IS 'Lookback window used for passageway record pulls.';
COMMENT ON COLUMN sessions.vendor_session_projection_sync_targets.page_size IS 'Vendor API page size used for passageway record pulls.';
COMMENT ON COLUMN sessions.vendor_session_projection_sync_targets.last_success_at IS 'Last successful projection sync completion timestamp.';
COMMENT ON COLUMN sessions.vendor_session_projection_sync_targets.last_failure_at IS 'Last failed projection sync completion timestamp.';
COMMENT ON COLUMN sessions.vendor_session_projection_sync_targets.last_attempt_at IS 'Last projection sync attempt timestamp.';
COMMENT ON COLUMN sessions.vendor_session_projection_sync_targets.health_status IS 'Operational target health: HEALTHY, DEGRADED, FAILING, DISABLED, DEFERRED, or UNKNOWN.';
COMMENT ON COLUMN sessions.vendor_session_projection_sync_targets.failure_count IS 'Consecutive failure count for this target.';
COMMENT ON COLUMN sessions.vendor_session_projection_sync_targets.last_error_code IS 'Last sync error code, when failed.';
COMMENT ON COLUMN sessions.vendor_session_projection_sync_targets.last_error_message IS 'Last sync error message, when failed.';
COMMENT ON COLUMN sessions.vendor_session_projection_sync_targets.last_lock_contention_at IS 'Last cycle deferred because another scheduler held the target-scoped advisory lock.';
COMMENT ON COLUMN sessions.vendor_session_projection_sync_targets.lock_contention_count IS 'Cumulative target-scoped advisory lock contention count.';
COMMENT ON COLUMN sessions.vendor_session_projection_sync_targets.correlation_id IS 'Correlation identifier for the last scheduler/manual attempt.';
COMMENT ON COLUMN sessions.vendor_session_projection_sync_targets.created_at IS 'Record creation timestamp.';
COMMENT ON COLUMN sessions.vendor_session_projection_sync_targets.updated_at IS 'Last update timestamp.';
COMMENT ON COLUMN sessions.vendor_session_projection_sync_targets.row_version IS 'Optimistic concurrency version.';
