COMMENT ON TABLE sessions.vendor_session_projections IS 'ExitPass-owned read model of latest-known vendor session continuity snapshots. This projection is not parking-session authority, tariff authority, payment finality, or exit authorization.';
COMMENT ON COLUMN sessions.vendor_session_projections.vendor_session_projection_id IS 'Canonical identifier of the projection snapshot.';
COMMENT ON COLUMN sessions.vendor_session_projections.vendor_system_id IS 'Vendor PMS that supplied the passageway source record, where mapped.';
COMMENT ON COLUMN sessions.vendor_session_projections.site_id IS 'ExitPass site scope, where mapped.';
COMMENT ON COLUMN sessions.vendor_session_projections.site_group_id IS 'ExitPass site group scope, where mapped.';
COMMENT ON COLUMN sessions.vendor_session_projections.source_adapter_identity_id IS 'Site Integration Adapter service identity that supplied the provider-neutral projection.';
COMMENT ON COLUMN sessions.vendor_session_projections.parking_lot_index_code IS 'HikCentral parking lot index code.';
COMMENT ON COLUMN sessions.vendor_session_projections.parking_lot_name IS 'HikCentral parking lot display name.';
COMMENT ON COLUMN sessions.vendor_session_projections.passageway_index_code IS 'HikCentral passageway index code.';
COMMENT ON COLUMN sessions.vendor_session_projections.passageway_name IS 'HikCentral passageway display name.';
COMMENT ON COLUMN sessions.vendor_session_projections.lane_index_code IS 'HikCentral lane index code.';
COMMENT ON COLUMN sessions.vendor_session_projections.lane_name IS 'HikCentral lane display name.';
COMMENT ON COLUMN sessions.vendor_session_projections.lane_direction IS 'HikCentral lane direction, where supplied.';
COMMENT ON COLUMN sessions.vendor_session_projections.vendor_record_guid IS 'HikCentral passageway record GUID, where supplied.';
COMMENT ON COLUMN sessions.vendor_session_projections.card_num IS 'HikCentral personInfo.cardNum value used as ticket/card lookup value.';
COMMENT ON COLUMN sessions.vendor_session_projections.plate_license IS 'Optional HikCentral plate license value.';
COMMENT ON COLUMN sessions.vendor_session_projections.enter_time IS 'Entry timestamp from the vendor passageway record.';
COMMENT ON COLUMN sessions.vendor_session_projections.exit_time IS 'Exit timestamp from the vendor passageway record.';
COMMENT ON COLUMN sessions.vendor_session_projections.allow_type IS 'Vendor allow type from the passageway record.';
COMMENT ON COLUMN sessions.vendor_session_projections.allow_result IS 'Vendor allow result from the passageway record.';
COMMENT ON COLUMN sessions.vendor_session_projections.image_url IS 'Vendor image URL reference, where supplied.';
COMMENT ON COLUMN sessions.vendor_session_projections.source_api IS 'Vendor source API path used to build the projection.';
COMMENT ON COLUMN sessions.vendor_session_projections.source_payload_hash IS 'SHA-256 hash of the normalized source payload; raw payload is not retained in this table.';
COMMENT ON COLUMN sessions.vendor_session_projections.source_payload_reference IS 'Safe source payload reference such as vendor record GUID or derived reference.';
COMMENT ON COLUMN sessions.vendor_session_projections.source_event_at IS 'Best available source event timestamp from enter/exit time.';
COMMENT ON COLUMN sessions.vendor_session_projections.stable_identity_type IS 'Stable identity strategy used for idempotent upsert.';
COMMENT ON COLUMN sessions.vendor_session_projections.stable_identity_key IS 'Stable projection identity key used for idempotent upsert.';
COMMENT ON COLUMN sessions.vendor_session_projections.first_seen_at IS 'First time ExitPass observed this projection identity.';
COMMENT ON COLUMN sessions.vendor_session_projections.last_seen_at IS 'Most recent time ExitPass observed this projection identity.';
COMMENT ON COLUMN sessions.vendor_session_projections.last_refreshed_at IS 'Most recent time ExitPass refreshed this projection snapshot.';
COMMENT ON COLUMN sessions.vendor_session_projections.projection_status IS 'Projection snapshot status: ACTIVE, EXITED, STALE, INVALIDATED, or UNKNOWN.';
COMMENT ON COLUMN sessions.vendor_session_projections.correlation_id IS 'Cross-service correlation identifier for the pull that last refreshed this projection.';
COMMENT ON COLUMN sessions.vendor_session_projections.created_at IS 'Record creation timestamp.';
COMMENT ON COLUMN sessions.vendor_session_projections.created_by_service_identity_id IS 'Service identity that created the projection.';
COMMENT ON COLUMN sessions.vendor_session_projections.updated_at IS 'Last update timestamp.';
COMMENT ON COLUMN sessions.vendor_session_projections.updated_by_service_identity_id IS 'Service identity that last updated the projection.';
COMMENT ON COLUMN sessions.vendor_session_projections.row_version IS 'Optimistic concurrency version.';
COMMENT ON CONSTRAINT uq_vendor_session_projections__target_stable_identity ON sessions.vendor_session_projections IS 'Idempotent projection identity isolated by Vendor System, Site Group, Site, and parking lot.';
