-- Create enum type "service_credential_type_enum"
CREATE TYPE "identity"."service_credential_type_enum" AS ENUM ('CLIENT_SECRET_REFERENCE', 'CERTIFICATE_REFERENCE', 'MTLS_CERTIFICATE_REFERENCE', 'API_KEY_REFERENCE', 'JWT_SIGNING_KEY_REFERENCE', 'KEY_VAULT_REFERENCE', 'WEBHOOK_SECRET_REFERENCE', 'NONE');;

