-- Create enum type "ttl_scope_type_enum"
CREATE TYPE "config"."ttl_scope_type_enum" AS ENUM ('TARIFF_SNAPSHOT', 'PAYMENT_ATTEMPT', 'PROVIDER_SESSION', 'COUPON_RESERVATION', 'STATUTORY_DISCOUNT_VALIDATION', 'SESSION_LOOKUP_CACHE', 'EXIT_AUTHORIZATION', 'PROVIDER_CALLBACK_REPLAY_WINDOW', 'EVIDENCE_RETENTION', 'OUTBOX_RETRY', 'CUSTOM');;

