-- Create enum type "reconciliation_run_type_enum"
CREATE TYPE "reconciliation"."reconciliation_run_type_enum" AS ENUM ('MOPS_RECONCILIATION', 'PROVIDER_SETTLEMENT', 'MANUAL_GATE_REVIEW', 'INCIDENT_RECONCILIATION', 'COUPON_WALLET_RECONCILIATION', 'PAYMENT_PROVIDER_RECONCILIATION', 'VENDOR_PMS_RECONCILIATION');;

