-- Create enum type "reconciliation_exception_type_enum"
CREATE TYPE "reconciliation"."reconciliation_exception_type_enum" AS ENUM ('AMOUNT_MISMATCH', 'MISSING_PAYMENT_CONFIRMATION', 'MISSING_PROVIDER_OUTCOME', 'MISSING_MOPS_RECORD', 'DUPLICATE_RECORD', 'MANUAL_GATE_WITHOUT_PAYMENT', 'SETTLEMENT_MISMATCH', 'COUPON_WALLET_MISMATCH', 'UNRESOLVED_CONTINUITY_RECORD', 'POLICY_EXCEPTION', 'UNKNOWN_EXCEPTION');;

