-- Create "outbox_events" table
CREATE TABLE "events"."outbox_events" (
  "outbox_event_id" uuid NOT NULL DEFAULT gen_random_uuid(),
  "domain_event_id" uuid NULL,
  "source_schema" character varying(64) NOT NULL,
  "source_table" character varying(96) NULL,
  "event_type" character varying(128) NOT NULL,
  "event_version" integer NOT NULL DEFAULT 1,
  "aggregate_type" character varying(96) NOT NULL,
  "aggregate_id" uuid NOT NULL,
  "routing_key" character varying(160) NOT NULL,
  "exchange_name" character varying(128) NULL,
  "payload_ref" character varying(256) NULL,
  "payload_hash" character(64) NULL,
  "payload_content_type" character varying(64) NOT NULL,
  "publication_status" "events"."outbox_publication_status_enum" NOT NULL,
  "available_at" timestamptz NOT NULL DEFAULT now(),
  "locked_at" timestamptz NULL,
  "locked_by_service_identity_id" uuid NULL,
  "published_at" timestamptz NULL,
  "next_retry_at" timestamptz NULL,
  "retry_count" integer NOT NULL DEFAULT 0,
  "max_retry_count" integer NOT NULL DEFAULT 10,
  "failure_reason_code" character varying(64) NULL,
  "correlation_id" uuid NULL,
  "causation_id" uuid NULL,
  "created_at" timestamptz NOT NULL DEFAULT now(),
  "created_by_service_identity_id" uuid NULL,
  "updated_at" timestamptz NOT NULL DEFAULT now(),
  "updated_by_service_identity_id" uuid NULL,
  "row_version" bigint NOT NULL DEFAULT 1,
  CONSTRAINT "pk_outbox_events" PRIMARY KEY ("outbox_event_id")
);;

