BEGIN;

ALTER TABLE core.fiscal_issuance_references
    DROP CONSTRAINT ck_fiscal_issuance_references__exception_reason;

ALTER TABLE core.fiscal_issuance_references
    ADD CONSTRAINT ck_fiscal_issuance_references__exception_reason CHECK (
        latest_exception_reason IS NULL
        OR latest_exception_reason IN (
            'MISSING_PAYABLE_BASIS',
            'MISSING_UPSTREAM_FINALITY_REFERENCE',
            'UNAPPROVED_DISCOUNT_REFERENCE',
            'UNSUPPORTED_FISCAL_DOCUMENT_REQUEST',
            'INVALID_FISCAL_TENDER',
            'MISSING_FISCAL_TENDER',
            'INVALID_FISCAL_TAX_DETAIL',
            'INVALID_FISCAL_DISCOUNT_PRIVILEGE_DETAIL',
            'INVALID_FISCAL_TOTAL',
            'SENSITIVE_PAYLOAD_REJECTED',
            'REQUEST_CONSTRUCTION_ERROR',
            'FISCAL_IDENTITY_NOT_FOUND',
            'FISCAL_IDENTITY_AMBIGUOUS',
            'FISCAL_IDENTITY_NOT_EFFECTIVE',
            'FISCAL_SEQUENCE_POLICY_NOT_FOUND',
            'FISCAL_SEQUENCE_POLICY_AMBIGUOUS',
            'FISCAL_SEQUENCE_POLICY_NOT_EFFECTIVE',
            'FISCAL_SEQUENCE_STATE_NOT_FOUND',
            'FISCAL_SEQUENCE_STATE_NOT_EFFECTIVE',
            'FISCAL_NUMBER_ALLOCATION_FAILED',
            'FISCAL_DOCUMENT_NUMBER_FORMAT_FAILED',
            'FISCAL_REPORTING_PERIOD_UNAVAILABLE',
            'FISCAL_REPORTING_PERIOD_AMBIGUOUS',
            'FISCAL_REPORTING_PERIOD_CLOSED',
            'FISCAL_REPORTING_PERIOD_ASSIGNMENT_MISMATCH',
            'FISCAL_DOCUMENT_IDEMPOTENCY_CONFLICT',
            'REPLAY_MISMATCH',
            'DUPLICATE_REFERENCE_DETECTED',
            'PERSISTENCE_NOT_CONFIGURED',
            'INVALID_PERSISTENCE_CONFIGURATION',
            'PERSISTENCE_WRITE_FAILED',
            'FISCAL_NUMBER_ASSIGNMENT_INCOMPLETE',
            'POST_TIMEOUT',
            'NETWORK_DISCONNECT_AFTER_POSSIBLE_COMMIT',
            'GET_READBACK_NOT_FOUND',
            'GET_READBACK_SERVICE_FAILED',
            'GET_READBACK_INCONCLUSIVE',
            'CENTRAL_PMS_REFERENCE_PERSISTENCE_FAILED',
            'MANUAL_REVIEW_REQUIRED',
            'MANUAL_RELEASE_REQUESTED_AFTER_FISCAL_FAILURE',
            'FISCAL_REFERENCE_MISMATCH',
            'RECONCILIATION_REQUIRED',
            'RECONCILIATION_CLOSED'
        )
    );

COMMIT;
