-- Create enum type "policy_source_type_enum"
CREATE TYPE "discounts"."policy_source_type_enum" AS ENUM ('OFFICIAL_LGU_DOCUMENT', 'OFFICIAL_LGU_CONFIRMATION', 'CONTROLLED_OFFLINE_AUTHORITY', 'SECONDARY_SOURCE', 'OPERATIONAL_OBSERVATION', 'NO_LOCAL_RULE_RECORD', 'STATUS_UNRESOLVED');;
