CREATE TYPE "discounts"."statutory_evidence_operation_type_enum" AS ENUM (
  'CREATE_SET',
  'ADD_ITEM',
  'AUTHORIZE_UPLOAD',
  'MARK_UPLOADED',
  'FINALIZE_UPLOAD',
  'RECORD_UPLOAD_VERIFICATION_FAILURE',
  'RECORD_VALIDATION',
  'RECORD_SCAN',
  'MARK_REVIEWABLE',
  'LOCK_FOR_REVIEW',
  'BIND_SET',
  'PLACE_HOLD',
  'RELEASE_HOLD',
  'REQUEST_DELETION',
  'RECORD_DELETION'
);;
