CREATE TYPE "discounts"."statutory_evidence_event_type_enum" AS ENUM (
  'EVIDENCE_SET_CREATED',
  'EVIDENCE_ITEM_CREATED',
  'IDEMPOTENT_REPLAY',
  'SEMANTIC_CONFLICT',
  'BINDING_ACCEPTED',
  'BINDING_REJECTED',
  'LIFECYCLE_TRANSITION',
  'REVIEW_LOCKED',
  'HOLD_PLACED',
  'HOLD_RELEASED',
  'DELETION_REQUESTED',
  'ACCESS_ALLOWED',
  'ACCESS_DENIED',
  'MALFORMED_REFERENCE_LOOKUP',
  'CROSS_SCOPE_ATTEMPT',
  'INVALID_TRANSITION'
);;
