-- Create "reconciliation_exceptions" table
CREATE TABLE "reconciliation"."reconciliation_exceptions" (
  "reconciliation_exception_id" uuid NOT NULL DEFAULT gen_random_uuid(),
  "reconciliation_run_id" uuid NOT NULL,
  "reconciliation_item_id" uuid NULL,
  "incident_record_id" uuid NULL,
  "exception_type" "reconciliation"."reconciliation_exception_type_enum" NOT NULL,
  "exception_severity" "reconciliation"."reconciliation_exception_severity_enum" NOT NULL,
  "exception_status" "reconciliation"."reconciliation_exception_status_enum" NOT NULL,
  "exception_reason_code" character varying(64) NOT NULL,
  "exception_summary" character varying(256) NOT NULL,
  "exception_detail" text NULL,
  "assigned_to_user_id" uuid NULL,
  "assigned_to_service_identity_id" uuid NULL,
  "created_from_status" character varying(64) NULL,
  "detected_at" timestamptz NOT NULL,
  "assigned_at" timestamptz NULL DEFAULT now(),
  "resolved_at" timestamptz NULL,
  "closed_at" timestamptz NULL,
  "resolution_reason_code" character varying(64) NULL,
  "closure_reason_code" character varying(64) NULL,
  "resolved_by_user_id" uuid NULL,
  "resolved_by_service_identity_id" uuid NULL,
  "closed_by_user_id" uuid NULL,
  "closed_by_service_identity_id" uuid NULL,
  "correlation_id" uuid NULL,
  "created_at" timestamptz NOT NULL DEFAULT now(),
  "created_by_user_id" uuid NULL,
  "created_by_service_identity_id" uuid NULL,
  "updated_at" timestamptz NOT NULL DEFAULT now(),
  "updated_by_user_id" uuid NULL,
  "updated_by_service_identity_id" uuid NULL,
  "row_version" bigint NOT NULL DEFAULT 1,
  CONSTRAINT "pk_reconciliation_exceptions" PRIMARY KEY ("reconciliation_exception_id")
);;

