-- Create "mops_transaction_records" table
CREATE TABLE "reconciliation"."mops_transaction_records" (
  "mops_transaction_record_id" uuid NOT NULL DEFAULT gen_random_uuid(),
  "parking_session_id" uuid NULL,
  "manual_gate_log_id" uuid NULL,
  "incident_record_id" uuid NULL,
  "site_id" uuid NOT NULL,
  "lane_id" uuid NULL,
  "source_system_code" character varying(64) NOT NULL,
  "source_transaction_ref" character varying(128) NULL,
  "source_batch_ref" character varying(128) NULL,
  "collection_reference" character varying(128) NULL,
  "currency_code" character(3) NULL,
  "amount" numeric(18,2) NULL,
  "payment_method_label" character varying(64) NULL,
  "continuity_reason_code" character varying(64) NOT NULL,
  "record_status" "reconciliation"."mops_transaction_record_status_enum" NOT NULL,
  "captured_at" timestamptz NOT NULL,
  "imported_at" timestamptz NULL,
  "reconciled_at" timestamptz NULL,
  "rejected_at" timestamptz NULL,
  "disputed_at" timestamptz NULL,
  "failure_reason_code" character varying(64) NULL,
  "evidence_ref" character varying(256) NULL,
  "evidence_hash" character(64) NULL,
  "captured_by_user_id" uuid NULL,
  "captured_by_service_identity_id" uuid NULL,
  "imported_by_service_identity_id" uuid NULL,
  "correlation_id" uuid NULL,
  "created_at" timestamptz NOT NULL DEFAULT now(),
  "created_by_user_id" uuid NULL,
  "created_by_service_identity_id" uuid NULL,
  "updated_at" timestamptz NOT NULL DEFAULT now(),
  "updated_by_user_id" uuid NULL,
  "updated_by_service_identity_id" uuid NULL,
  "row_version" bigint NOT NULL DEFAULT 1,
  CONSTRAINT "pk_mops_transaction_records" PRIMARY KEY ("mops_transaction_record_id")
);;

