-- Create "reconciliation_runs" table
CREATE TABLE "reconciliation"."reconciliation_runs" (
  "reconciliation_run_id" uuid NOT NULL DEFAULT gen_random_uuid(),
  "run_code" character varying(64) NOT NULL,
  "run_type" "reconciliation"."reconciliation_run_type_enum" NOT NULL,
  "run_status" "reconciliation"."reconciliation_run_status_enum" NOT NULL,
  "scope_type" "reconciliation"."reconciliation_scope_type_enum" NOT NULL,
  "site_group_id" uuid NULL,
  "site_id" uuid NULL,
  "incident_record_id" uuid NULL,
  "payment_rail_id" uuid NULL,
  "vendor_system_id" uuid NULL,
  "source_batch_ref" character varying(128) NULL,
  "window_start_at" timestamptz NULL,
  "window_end_at" timestamptz NULL,
  "started_at" timestamptz NOT NULL DEFAULT now(),
  "completed_at" timestamptz NULL,
  "failed_at" timestamptz NULL,
  "failure_reason_code" character varying(64) NULL,
  "item_count" integer NOT NULL,
  "matched_count" integer NOT NULL,
  "exception_count" integer NOT NULL,
  "rejected_count" integer NOT NULL,
  "disputed_count" integer NOT NULL,
  "initiated_by_user_id" uuid NULL,
  "initiated_by_service_identity_id" uuid NULL,
  "correlation_id" uuid NULL,
  "created_at" timestamptz NOT NULL DEFAULT now(),
  "created_by_user_id" uuid NULL,
  "created_by_service_identity_id" uuid NULL,
  "updated_at" timestamptz NOT NULL DEFAULT now(),
  "updated_by_user_id" uuid NULL,
  "updated_by_service_identity_id" uuid NULL,
  "row_version" bigint NOT NULL DEFAULT 1,
  CONSTRAINT "pk_reconciliation_runs" PRIMARY KEY ("reconciliation_run_id")
);;

