-- Create "statutory_discount_decision_policy_authorities" table
CREATE TABLE "discounts"."statutory_discount_decision_policy_authorities" (
  "statutory_discount_decision_command_id" uuid NOT NULL,
  "statutory_discount_policy_version_id" uuid NOT NULL,
  "jurisdiction_id" uuid NOT NULL,
  "jurisdiction_code" character varying(64) NOT NULL,
  "jurisdiction_display_name" character varying(160) NOT NULL,
  "policy_code" character varying(128) NOT NULL,
  "policy_version" character varying(64) NOT NULL,
  "entitlement_type" character varying(64) NOT NULL,
  "source_verification_status" "discounts"."policy_verification_status_enum" NOT NULL,
  "transaction_publication_status" "discounts"."statutory_policy_publication_status_enum" NOT NULL,
  "detailed_rule_verification_status" "discounts"."policy_detail_verification_status_enum" NOT NULL,
  "parking_service_applicability" "discounts"."parking_service_applicability_status_enum" NOT NULL,
  "benefit_type" "discounts"."parking_benefit_type_enum" NOT NULL,
  "beneficiary_residency_scope" "discounts"."beneficiary_residency_scope_enum" NOT NULL,
  "official_source_available" boolean NULL,
  "ordinance_text_available" boolean NULL,
  "ordinance_number_available" boolean NULL,
  "ordinance_number" character varying(128) NULL,
  "ordinance_title" character varying(256) NULL,
  "legal_basis_reference" character varying(256) NULL,
  "source_reference" text NOT NULL,
  "transaction_use_effective_from" timestamptz NULL,
  "transaction_use_effective_to" timestamptz NULL,
  "resolved_at" timestamptz NOT NULL DEFAULT now(),
  "policy_authority_semantic_hash" character varying(80) NOT NULL,
  "policy_authority_semantic_hash_source_version" character varying(80) NOT NULL DEFAULT 'statutory-decision-policy-authority:sha256:v1',
  "correlation_id" uuid NULL,
  "created_at" timestamptz NOT NULL DEFAULT now(),
  "updated_at" timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT "pk_statutory_discount_decision_policy_authorities" PRIMARY KEY ("statutory_discount_decision_command_id"),
  CONSTRAINT "fk_sd_decision_policy_authorities__decision" FOREIGN KEY ("statutory_discount_decision_command_id") REFERENCES "discounts"."statutory_discount_decision_commands" ("statutory_discount_decision_command_id"),
  CONSTRAINT "fk_sd_decision_policy_authorities__policy_version" FOREIGN KEY ("statutory_discount_policy_version_id") REFERENCES "discounts"."statutory_discount_policy_versions" ("statutory_discount_policy_version_id"),
  CONSTRAINT "fk_sd_decision_policy_authorities__jurisdiction" FOREIGN KEY ("jurisdiction_id") REFERENCES "sites"."jurisdictions" ("jurisdiction_id"),
  CONSTRAINT "ck_sd_decision_policy_authorities__entitlement" CHECK (entitlement_type IN ('SENIOR_CITIZEN', 'PWD')),
  CONSTRAINT "ck_sd_decision_policy_authorities__source_reference" CHECK (btrim(source_reference) <> ''::text),
  CONSTRAINT "ck_sd_decision_policy_authorities__hash" CHECK ((policy_authority_semantic_hash)::text ~ '^sha256:[0-9a-f]{64}$'::text),
  CONSTRAINT "ck_sd_decision_policy_authorities__hash_version" CHECK ((policy_authority_semantic_hash_source_version)::text = 'statutory-decision-policy-authority:sha256:v1'::text),
  CONSTRAINT "ck_sd_decision_policy_authorities__active_authority" CHECK (transaction_publication_status = 'ACTIVE_FOR_TRANSACTION_USE'::discounts.statutory_policy_publication_status_enum AND parking_service_applicability = 'COVERED'::discounts.parking_service_applicability_status_enum)
);;
