-- Create "statutory_discount_decision_commands" table
CREATE TABLE "discounts"."statutory_discount_decision_commands" (
  "statutory_discount_decision_command_id" uuid NOT NULL DEFAULT gen_random_uuid(),
  "request_reference" uuid NOT NULL,
  "parking_session_id" uuid NOT NULL,
  "source_channel" character varying(64) NOT NULL,
  "entitlement_type" character varying(64) NOT NULL,
  "business_identity" character varying(256) NULL,
  "idempotency_scope" character varying(256) NOT NULL,
  "idempotency_key" character varying(128) NOT NULL,
  "semantic_request_hash" character varying(80) NOT NULL,
  "semantic_hash_source_version" character varying(64) NOT NULL,
  "statutory_discount_validation_id" uuid NULL,
  "payable_basis_application_id" uuid NULL,
  "original_tariff_snapshot_id" uuid NULL,
  "applied_tariff_snapshot_id" uuid NULL,
  "decision_status" character varying(64) NOT NULL,
  "command_status" character varying(64) NOT NULL DEFAULT 'PROCESSING',
  "decision_result_status" character varying(64) NOT NULL DEFAULT 'NOT_DECIDED',
  "result_classification" character varying(64) NOT NULL,
  "retryable" boolean NOT NULL DEFAULT false,
  "recovery_classification" character varying(80) NOT NULL DEFAULT 'NONE',
  "policy_resolution_basis" character varying(80) NULL,
  "applied_policy_reference_id" uuid NULL,
  "fallback_policy_reference_id" uuid NULL,
  "local_ordinance_applied" boolean NOT NULL DEFAULT false,
  "gross_amount_minor_units" bigint NULL,
  "vat_exclusive_amount_minor_units" bigint NULL,
  "vat_amount_minor_units" bigint NULL,
  "statutory_discount_amount_minor_units" bigint NULL,
  "net_payable_amount_minor_units" bigint NULL,
  "currency_code" character(3) NULL,
  "evidence_required" boolean NOT NULL DEFAULT false,
  "evidence_recorded" boolean NOT NULL DEFAULT false,
  "reason_code" character varying(128) NULL,
  "error_code" character varying(128) NULL,
  "original_correlation_id" uuid NOT NULL,
  "created_at" timestamptz NOT NULL DEFAULT now(),
  "processing_started_at" timestamptz NULL,
  "decided_at" timestamptz NULL,
  "applied_at" timestamptz NULL,
  "completed_at" timestamptz NULL,
  "failed_at" timestamptz NULL,
  "updated_at" timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT "pk_statutory_discount_decision_commands" PRIMARY KEY ("statutory_discount_decision_command_id"),
  CONSTRAINT "fk_statutory_discount_decision_commands__parking_session" FOREIGN KEY ("parking_session_id") REFERENCES "core"."parking_sessions" ("parking_session_id"),
  CONSTRAINT "fk_statutory_discount_decision_commands__validation" FOREIGN KEY ("statutory_discount_validation_id") REFERENCES "discounts"."statutory_discount_validations" ("statutory_discount_validation_id"),
  CONSTRAINT "fk_statutory_discount_decision_commands__payable_basis_application" FOREIGN KEY ("payable_basis_application_id") REFERENCES "discounts"."statutory_discount_payable_basis_applications" ("statutory_discount_payable_basis_application_id"),
  CONSTRAINT "fk_statutory_discount_decision_commands__original_tariff_snapshot" FOREIGN KEY ("original_tariff_snapshot_id") REFERENCES "core"."tariff_snapshots" ("tariff_snapshot_id"),
  CONSTRAINT "fk_statutory_discount_decision_commands__applied_tariff_snapshot" FOREIGN KEY ("applied_tariff_snapshot_id") REFERENCES "core"."tariff_snapshots" ("tariff_snapshot_id"),
  CONSTRAINT "ck_statutory_discount_decision_commands__source_channel" CHECK (source_channel IN ('OPERATOR_CONSOLE', 'WEBPAY', 'ASSISTED_PAYMENT_TERMINAL')),
  CONSTRAINT "ck_statutory_discount_decision_commands__entitlement_type" CHECK (entitlement_type IN ('SENIOR_CITIZEN', 'PWD')),
  CONSTRAINT "ck_statutory_discount_decision_commands__hash" CHECK (semantic_request_hash ~ '^sha256:[0-9a-f]{64}$'),
  CONSTRAINT "ck_statutory_discount_decision_commands__semantic_version" CHECK (semantic_hash_source_version IN ('statutory-discount-decision:sha256:v1', 'statutory-discount-decision:sha256:v2')),
  CONSTRAINT "ck_statutory_discount_decision_commands__decision_status" CHECK (decision_status IN ('PROCESSING', 'REQUESTED', 'PENDING_OPERATOR_REVIEW', 'APPROVED', 'REJECTED', 'FAILED', 'EXPIRED', 'CANCELLED', 'APPLIED_PAYABLE_BASIS')),
  CONSTRAINT "ck_statutory_discount_decision_commands__command_status" CHECK (command_status IN ('RECEIVED', 'PROCESSING', 'AWAITING_REVIEW', 'COMPLETED', 'FAILED_RETRYABLE', 'FAILED_NON_RETRYABLE')),
  CONSTRAINT "ck_statutory_discount_decision_commands__decision_result_status" CHECK (decision_result_status IN ('APPROVED', 'REJECTED', 'NOT_DECIDED')),
  CONSTRAINT "ck_statutory_discount_decision_commands__result_classification" CHECK (result_classification IN ('ACCEPTED', 'IDEMPOTENT_REPLAY', 'AWAITING_REVIEW')),
  CONSTRAINT "ck_stat_disc_decision_cmds__recovery" CHECK (recovery_classification IN ('NONE', 'AWAITING_REVIEW', 'READ_CANONICAL_RESULT', 'RETRY_ORIGINAL_IDEMPOTENCY_KEY', 'WAIT_THEN_RETRY_ORIGINAL_IDEMPOTENCY_KEY', 'CORRECT_REQUEST_REQUIRED', 'NOT_RECOVERABLE'))
);;
