-- Create "statutory_discount_policy_registry" table
CREATE TABLE "discounts"."statutory_discount_policy_registry" (
  "statutory_discount_policy_registry_id" uuid NOT NULL DEFAULT gen_random_uuid(),
  "policy_code" character varying(128) NOT NULL,
  "policy_name" character varying(256) NOT NULL,
  "policy_description" text NULL,
  "entitlement_type" "discounts"."statutory_entitlement_type_enum" NOT NULL,
  "policy_status" "discounts"."discount_policy_status_enum" NOT NULL,
  "verification_status" "discounts"."policy_verification_status_enum" NOT NULL,
  "policy_level" "discounts"."discount_policy_level_enum" NOT NULL,
  "policy_type" "discounts"."discount_policy_type_enum" NOT NULL,
  "policy_resolution_basis" "discounts"."policy_resolution_basis_enum" NOT NULL,
  "benefit_type" "discounts"."parking_benefit_type_enum" NOT NULL,
  "discount_base_scope" "discounts"."discount_base_scope_enum" NOT NULL,
  "jurisdiction_id" uuid NULL,
  "local_government_unit_id" uuid NULL,
  "jurisdiction_code" character varying(64) NULL,
  "jurisdiction_name" character varying(160) NULL,
  "site_group_id" uuid NULL,
  "site_id" uuid NULL,
  "beneficiary_residency_scope" "discounts"."beneficiary_residency_scope_enum" NOT NULL,
  "facility_scope" text NULL,
  "free_duration_minutes" integer NULL,
  "initial_rate_exempt" boolean NOT NULL DEFAULT false,
  "full_fee_exempt" boolean NOT NULL DEFAULT false,
  "overnight_excluded" boolean NOT NULL DEFAULT false,
  "valet_excluded" boolean NOT NULL DEFAULT false,
  "standalone_parking_excluded" boolean NOT NULL DEFAULT false,
  "driver_or_passenger_required" boolean NOT NULL DEFAULT false,
  "coverage_available" boolean NOT NULL DEFAULT false,
  "auto_application_allowed" boolean NOT NULL DEFAULT false,
  "source_scan_date" date NULL,
  "source_document_available" boolean NULL,
  "requires_evidence" boolean NOT NULL DEFAULT true,
  "required_evidence_type" "discounts"."discount_evidence_type_enum" NULL,
  "requires_operator_validation" boolean NOT NULL DEFAULT true,
  "legal_basis_reference" character varying(256) NULL,
  "ordinance_reference" character varying(256) NULL,
  "national_law_reference" character varying(128) NULL,
  "source_reference" text NOT NULL,
  "source_document_hash" character varying(128) NULL,
  "reviewed_by_user_id" uuid NULL,
  "reviewed_by" character varying(128) NULL,
  "reviewed_at" timestamptz NULL,
  "approved_by_user_id" uuid NULL,
  "approved_by" character varying(128) NULL,
  "approved_at" timestamptz NULL,
  "effective_from" timestamptz NOT NULL,
  "effective_to" timestamptz NULL,
  "supersedes_policy_id" uuid NULL,
  "superseded_by_policy_id" uuid NULL,
  "notes" text NULL,
  "correlation_id" uuid NULL,
  "created_at" timestamptz NOT NULL DEFAULT now(),
  "created_by_user_id" uuid NULL,
  "created_by_service_identity_id" uuid NULL,
  "updated_at" timestamptz NOT NULL DEFAULT now(),
  "updated_by_user_id" uuid NULL,
  "updated_by_service_identity_id" uuid NULL,
  "row_version" bigint NOT NULL DEFAULT 1,
  CONSTRAINT "pk_statutory_discount_policy_registry" PRIMARY KEY ("statutory_discount_policy_registry_id"),
  CONSTRAINT "uq_sd_policy_registry__policy_code" UNIQUE ("policy_code"),
  CONSTRAINT "ck_sd_policy_registry__policy_code_format" CHECK (((policy_code)::text = upper((policy_code)::text) AND ((policy_code)::text ~ '^[A-Z0-9][A-Z0-9_]{2,127}$'::text))),
  CONSTRAINT "ck_sd_policy_registry__effective_window" CHECK (((effective_to IS NULL) OR (effective_to > effective_from))),
  CONSTRAINT "ck_sd_policy_registry__source_reference_required" CHECK ((btrim(source_reference) <> ''::text)),
  CONSTRAINT "ck_sd_policy_registry__row_version_positive" CHECK ((row_version > 0)),
  CONSTRAINT "ck_sd_policy_registry__free_duration_non_negative" CHECK (((free_duration_minutes IS NULL) OR (free_duration_minutes >= 0))),
  CONSTRAINT "ck_sd_policy_registry__lgu_consistency" CHECK ((local_government_unit_id IS NULL) OR (jurisdiction_id IS NULL) OR (local_government_unit_id = jurisdiction_id)),
  CONSTRAINT "ck_sd_policy_registry__no_rule_not_available" CHECK ((verification_status <> 'NO_LOCAL_RULE_FOUND'::discounts.policy_verification_status_enum) OR (coverage_available = false)),
  CONSTRAINT "ck_sd_policy_registry__auto_requires_active_verified" CHECK ((auto_application_allowed = false) OR ((coverage_available = true) AND (policy_status = 'ACTIVE'::discounts.discount_policy_status_enum) AND (verification_status = ANY (ARRAY['VERIFIED_OFFICIAL'::discounts.policy_verification_status_enum, 'VERIFIED_ACTIVE_OPERATIONAL'::discounts.policy_verification_status_enum, 'ACTIVE_APPROVED'::discounts.policy_verification_status_enum])))),
  CONSTRAINT "ck_sd_policy_registry__evidence_type_required" CHECK (((requires_evidence = false) OR (required_evidence_type IS NOT NULL))),
  CONSTRAINT "ck_sd_policy_registry__reviewed_metadata" CHECK (((verification_status <> ALL (ARRAY['VERIFIED_SECONDARY'::discounts.policy_verification_status_enum, 'VERIFIED_OFFICIAL'::discounts.policy_verification_status_enum, 'APPROVED_FOR_PILOT'::discounts.policy_verification_status_enum, 'ACTIVE_APPROVED'::discounts.policy_verification_status_enum])) OR (((reviewed_by_user_id IS NOT NULL) OR (btrim((COALESCE(reviewed_by, ''::character varying))::text) <> ''::text)) AND (reviewed_at IS NOT NULL)))),
  CONSTRAINT "ck_sd_policy_registry__approved_metadata" CHECK (((verification_status <> ALL (ARRAY['APPROVED_FOR_PILOT'::discounts.policy_verification_status_enum, 'ACTIVE_APPROVED'::discounts.policy_verification_status_enum])) OR (((approved_by_user_id IS NOT NULL) OR (btrim((COALESCE(approved_by, ''::character varying))::text) <> ''::text)) AND (approved_at IS NOT NULL)))),
  CONSTRAINT "ck_sd_policy_registry__active_approved_status" CHECK (((verification_status <> 'ACTIVE_APPROVED'::discounts.policy_verification_status_enum) OR (policy_status = 'ACTIVE'::discounts.discount_policy_status_enum))),
  CONSTRAINT "ck_sd_policy_registry__proposed_not_active" CHECK (((verification_status <> 'PROPOSED_ONLY'::discounts.policy_verification_status_enum) OR (policy_status <> 'ACTIVE'::discounts.discount_policy_status_enum))),
  CONSTRAINT "ck_sd_policy_registry__active_legal_reference" CHECK (((verification_status <> 'ACTIVE_APPROVED'::discounts.policy_verification_status_enum) OR (COALESCE(btrim((legal_basis_reference)::text), btrim((ordinance_reference)::text), btrim((national_law_reference)::text)) IS NOT NULL))),
  CONSTRAINT "ck_sd_policy_registry__local_scope_reference" CHECK ((((policy_level <> 'LOCAL_ORDINANCE'::discounts.discount_policy_level_enum) AND (policy_resolution_basis <> 'LOCAL_ORDINANCE_APPLIED'::discounts.policy_resolution_basis_enum)) OR ((jurisdiction_id IS NOT NULL) OR (btrim((COALESCE(jurisdiction_code, ''::character varying))::text) <> ''::text) OR (site_group_id IS NOT NULL) OR (site_id IS NOT NULL)))),
  CONSTRAINT "ck_sd_policy_registry__national_reference" CHECK ((((policy_level <> 'NATIONAL_LAW'::discounts.discount_policy_level_enum) AND (policy_resolution_basis <> 'NATIONAL_LAW_FALLBACK'::discounts.policy_resolution_basis_enum)) OR (btrim((COALESCE(national_law_reference, ''::character varying))::text) <> ''::text))),
  CONSTRAINT "ck_sd_policy_registry__senior_national_law" CHECK (((policy_resolution_basis <> 'NATIONAL_LAW_FALLBACK'::discounts.policy_resolution_basis_enum) OR (entitlement_type <> 'SENIOR_CITIZEN'::discounts.statutory_entitlement_type_enum) OR ((national_law_reference)::text = 'RA 9994'::text))),
  CONSTRAINT "ck_sd_policy_registry__pwd_national_law" CHECK (((policy_resolution_basis <> 'NATIONAL_LAW_FALLBACK'::discounts.policy_resolution_basis_enum) OR (entitlement_type <> 'PWD'::discounts.statutory_entitlement_type_enum) OR ((national_law_reference)::text = 'RA 10754'::text))),
  CONSTRAINT "ck_sd_policy_registry__senior_evidence" CHECK (((requires_evidence = false) OR (entitlement_type <> 'SENIOR_CITIZEN'::discounts.statutory_entitlement_type_enum) OR (required_evidence_type = 'SENIOR_CITIZEN_ID'::discounts.discount_evidence_type_enum))),
  CONSTRAINT "ck_sd_policy_registry__pwd_evidence" CHECK (((requires_evidence = false) OR (entitlement_type <> 'PWD'::discounts.statutory_entitlement_type_enum) OR (required_evidence_type = 'PWD_ID'::discounts.discount_evidence_type_enum))),
  CONSTRAINT "ck_sd_policy_registry__no_prod_test_markers" CHECK (((verification_status <> 'ACTIVE_APPROVED'::discounts.policy_verification_status_enum) OR ((upper((policy_code)::text) !~~ '%SANDBOX%'::text) AND (upper((policy_code)::text) !~~ '%TEST%'::text) AND (upper((policy_code)::text) !~~ '%DEV%'::text) AND (upper((policy_code)::text) !~~ '%E2E%'::text) AND (upper((policy_code)::text) !~~ 'EXAMPLE%'::text) AND (upper((policy_name)::text) !~~ '%SANDBOX%'::text) AND (upper((policy_name)::text) !~~ '%TEST%'::text) AND (upper((policy_name)::text) !~~ '%DEV%'::text) AND (upper((policy_name)::text) !~~ '%E2E%'::text) AND (upper((policy_name)::text) !~~ 'EXAMPLE%'::text))))
);;

