-- Create "discount_policy_references" table
CREATE TABLE "discounts"."discount_policy_references" (
  "discount_policy_reference_id" uuid NOT NULL DEFAULT gen_random_uuid(),
  "policy_code" character varying(64) NOT NULL,
  "policy_name" character varying(256) NOT NULL,
  "policy_description" text NULL,
  "policy_type" "discounts"."discount_policy_type_enum" NOT NULL,
  "policy_level" "discounts"."discount_policy_level_enum" NOT NULL,
  "entitlement_type" "discounts"."statutory_entitlement_type_enum" NOT NULL,
  "national_law_reference" character varying(128) NULL,
  "local_ordinance_reference" character varying(128) NULL,
  "lgu_code" character varying(32) NULL,
  "jurisdiction_name" character varying(128) NULL,
  "site_group_id" uuid NULL,
  "site_id" uuid NULL,
  "parent_policy_reference_id" uuid NULL,
  "fallback_policy_reference_id" uuid NULL,
  "precedence_rank" integer NOT NULL,
  "policy_version" character varying(32) NOT NULL,
  "requires_operator_validation" boolean NOT NULL DEFAULT false,
  "requires_evidence_capture" boolean NOT NULL DEFAULT false,
  "evidence_retention_policy_code" character varying(64) NULL,
  "policy_status" "discounts"."discount_policy_status_enum" NOT NULL,
  "effective_from" timestamptz NOT NULL,
  "effective_to" timestamptz NULL,
  "created_at" timestamptz NOT NULL DEFAULT now(),
  "created_by_user_id" uuid NULL,
  "created_by_service_identity_id" uuid NULL,
  "updated_at" timestamptz NOT NULL DEFAULT now(),
  "updated_by_user_id" uuid NULL,
  "updated_by_service_identity_id" uuid NULL,
  "row_version" bigint NOT NULL DEFAULT 1,
  CONSTRAINT "pk_discount_policy_references" PRIMARY KEY ("discount_policy_reference_id"),
  CONSTRAINT "uq_discount_policy_references__policy_code_version" UNIQUE ("policy_code", "policy_version")
);;

