-- Create "statutory_discount_policy_import_review_submissions" table
CREATE TABLE "discounts"."statutory_discount_policy_import_review_submissions" (
  "review_submission_id" uuid NOT NULL DEFAULT gen_random_uuid(),
  "submission_code" character varying(96) NOT NULL,
  "correlation_id" uuid NULL,
  "source_file_name" character varying(256) NULL,
  "source_file_sha256" character varying(64) NULL,
  "submitted_by_operator_user_id" uuid NULL,
  "submitted_by_display_name" character varying(128) NULL,
  "dry_run_summary_json" jsonb NOT NULL,
  "sanitized_row_results_json" jsonb NOT NULL,
  "total_rows" integer NOT NULL DEFAULT 0,
  "pass_count" integer NOT NULL DEFAULT 0,
  "warn_count" integer NOT NULL DEFAULT 0,
  "fail_count" integer NOT NULL DEFAULT 0,
  "importable_count" integer NOT NULL DEFAULT 0,
  "manual_review_count" integer NOT NULL DEFAULT 0,
  "not_importable_count" integer NOT NULL DEFAULT 0,
  "duplicate_count" integer NOT NULL DEFAULT 0,
  "status" "discounts"."policy_import_review_status_enum" NOT NULL,
  "status_reason" text NULL,
  "current_required_reviewer_role" "discounts"."policy_import_review_role_enum" NULL,
  "created_at" timestamptz NOT NULL DEFAULT now(),
  "updated_at" timestamptz NOT NULL DEFAULT now(),
  "submitted_at" timestamptz NULL,
  "closed_at" timestamptz NULL,
  "superseded_by_review_submission_id" uuid NULL,
  "row_version" bigint NOT NULL DEFAULT 1,
  CONSTRAINT "pk_sd_policy_import_review_submissions" PRIMARY KEY ("review_submission_id"),
  CONSTRAINT "uq_sd_policy_import_review_submissions__code" UNIQUE ("submission_code"),
  CONSTRAINT "ck_sd_policy_import_review_submissions__code_format" CHECK (((submission_code)::text = upper((submission_code)::text) AND ((submission_code)::text ~ '^[A-Z0-9][A-Z0-9_-]{2,95}$'::text))),
  CONSTRAINT "ck_sd_policy_import_review_submissions__counts_non_negative" CHECK (((total_rows >= 0) AND (pass_count >= 0) AND (warn_count >= 0) AND (fail_count >= 0) AND (importable_count >= 0) AND (manual_review_count >= 0) AND (not_importable_count >= 0) AND (duplicate_count >= 0))),
  CONSTRAINT "ck_sd_policy_import_review_submissions__no_failed_alignment" CHECK (((status <> 'APPROVED_FOR_DB_REPO_ALIGNMENT'::discounts.policy_import_review_status_enum) OR (fail_count = 0))),
  CONSTRAINT "ck_sd_policy_import_review_submissions__terminal_closed_at" CHECK (((status <> ALL (ARRAY['APPROVED_FOR_DB_REPO_ALIGNMENT'::discounts.policy_import_review_status_enum, 'REJECTED'::discounts.policy_import_review_status_enum, 'CANCELLED'::discounts.policy_import_review_status_enum, 'SUPERSEDED'::discounts.policy_import_review_status_enum])) OR (closed_at IS NOT NULL))),
  CONSTRAINT "ck_sd_policy_import_review_submissions__source_sha256" CHECK (((source_file_sha256 IS NULL) OR ((source_file_sha256)::text ~ '^[A-Fa-f0-9]{64}$'::text))),
  CONSTRAINT "ck_sd_policy_import_review_submissions__dry_run_json" CHECK ((jsonb_typeof(dry_run_summary_json) = 'object'::text)),
  CONSTRAINT "ck_sd_policy_import_review_submissions__row_results_json" CHECK ((jsonb_typeof(sanitized_row_results_json) = ANY (ARRAY['array'::text, 'object'::text]))),
  CONSTRAINT "ck_sd_policy_import_review_submissions__row_version_positive" CHECK ((row_version > 0))
);;

