-- Create "statutory_discount_validations" table
CREATE TABLE "discounts"."statutory_discount_validations" (
  "statutory_discount_validation_id" uuid NOT NULL DEFAULT gen_random_uuid(),
  "parking_session_id" uuid NOT NULL,
  "tariff_snapshot_id" uuid NULL,
  "entitlement_type" "discounts"."statutory_entitlement_type_enum" NOT NULL,
  "evaluated_policy_reference_id" uuid NULL,
  "applied_policy_reference_id" uuid NULL,
  "fallback_policy_reference_id" uuid NULL,
  "policy_resolution_basis" "discounts"."policy_resolution_basis_enum" NOT NULL,
  "local_ordinance_applied" boolean NOT NULL DEFAULT false,
  "national_law_fallback_applied" boolean NOT NULL DEFAULT false,
  "validation_channel" "discounts"."statutory_discount_validations_channel_enum" NOT NULL,
  "validation_status" "discounts"."statutory_discount_validations_status_enum" NOT NULL,
  "currency_code" character(3) NULL,
  "gross_amount_at_validation" numeric(18,2) NULL,
  "statutory_discount_amount" numeric(18,2) NULL,
  "net_amount_after_discount" numeric(18,2) NULL,
  "evidence_required" boolean NOT NULL DEFAULT false,
  "evidence_captured" boolean NOT NULL DEFAULT false,
  "decision_reason_code" character varying(64) NULL,
  "failure_reason_code" character varying(64) NULL,
  "requested_at" timestamptz NOT NULL,
  "validated_at" timestamptz NULL,
  "expires_at" timestamptz NULL,
  "validated_by_user_id" uuid NULL,
  "validated_by_service_identity_id" uuid NULL,
  "requested_by_user_id" uuid NULL,
  "requested_by_service_identity_id" uuid NULL,
  "correlation_id" uuid NULL,
  "created_at" timestamptz NOT NULL DEFAULT now(),
  "created_by_user_id" uuid NULL,
  "created_by_service_identity_id" uuid NULL,
  "updated_at" timestamptz NOT NULL DEFAULT now(),
  "updated_by_user_id" uuid NULL,
  "updated_by_service_identity_id" uuid NULL,
  "row_version" bigint NOT NULL DEFAULT 1,
  CONSTRAINT "pk_statutory_discount_validations" PRIMARY KEY ("statutory_discount_validation_id")
);;

