-- Create "statutory_discount_policy_versions" table
CREATE TABLE "discounts"."statutory_discount_policy_versions" (
  "statutory_discount_policy_version_id" uuid NOT NULL DEFAULT gen_random_uuid(),
  "statutory_discount_policy_registry_id" uuid NOT NULL,
  "policy_code" character varying(128) NOT NULL,
  "policy_version" character varying(64) NOT NULL,
  "policy_version_label" character varying(160) NULL,
  "entitlement_type" "discounts"."statutory_entitlement_type_enum" NOT NULL,
  "jurisdiction_id" uuid NOT NULL,
  "local_government_unit_id" uuid NULL,
  "jurisdiction_code" character varying(64) NOT NULL,
  "jurisdiction_display_name" character varying(160) NOT NULL,
  "policy_scope_type" "discounts"."policy_scope_type_enum" NOT NULL,
  "site_group_id" uuid NULL,
  "site_id" uuid NULL,
  "policy_level" "discounts"."discount_policy_level_enum" NOT NULL,
  "policy_type" "discounts"."discount_policy_type_enum" NOT NULL,
  "policy_resolution_basis" "discounts"."policy_resolution_basis_enum" NOT NULL DEFAULT 'LOCAL_ORDINANCE_APPLIED',
  "source_verification_status" "discounts"."policy_verification_status_enum" NOT NULL,
  "transaction_publication_status" "discounts"."statutory_policy_publication_status_enum" NOT NULL DEFAULT 'DRAFT',
  "detailed_rule_verification_status" "discounts"."policy_detail_verification_status_enum" NOT NULL DEFAULT 'STATUS_UNRESOLVED',
  "parking_service_applicability" "discounts"."parking_service_applicability_status_enum" NOT NULL DEFAULT 'UNRESOLVED',
  "benefit_type" "discounts"."parking_benefit_type_enum" NOT NULL,
  "policy_effect_support_status" "discounts"."policy_effect_support_status_enum" NOT NULL DEFAULT 'UNRESOLVED',
  "discount_base_scope" "discounts"."discount_base_scope_enum" NOT NULL,
  "beneficiary_residency_scope" "discounts"."beneficiary_residency_scope_enum" NOT NULL,
  "official_source_identified" boolean NULL,
  "official_source_available" boolean NULL,
  "ordinance_text_available" boolean NULL,
  "ordinance_number_available" boolean NULL,
  "ordinance_title_available" boolean NULL,
  "ordinance_number" character varying(128) NULL,
  "ordinance_title" character varying(256) NULL,
  "legal_basis_reference" character varying(256) NULL,
  "source_type" "discounts"."policy_source_type_enum" NOT NULL DEFAULT 'STATUS_UNRESOLVED',
  "source_reference" text NOT NULL,
  "source_document_reference" character varying(512) NULL,
  "source_document_hash" character varying(128) NULL,
  "source_retrieved_at" timestamptz NULL,
  "source_verified_at" timestamptz NULL,
  "unresolved_policy_facts" text NULL,
  "safe_channel_summary" text NULL,
  "safe_reviewer_guidance" text NULL,
  "facility_scope" text NULL,
  "standalone_parking_excluded" boolean NULL,
  "valet_excluded" boolean NULL,
  "overnight_excluded" boolean NULL,
  "driver_or_passenger_required" boolean NULL,
  "discount_percentage_basis_points" integer NULL,
  "free_duration_minutes" integer NULL,
  "cap_amount_minor_units" bigint NULL,
  "cap_currency_code" character(3) NULL,
  "full_fee_exempt" boolean NULL,
  "initial_rate_exempt" boolean NULL,
  "enactment_date" date NULL,
  "legal_effective_from" timestamptz NULL,
  "legal_effective_to" timestamptz NULL,
  "operational_confirmed_at" timestamptz NULL,
  "transaction_use_effective_from" timestamptz NULL,
  "transaction_use_effective_to" timestamptz NULL,
  "suspension_starts_at" timestamptz NULL,
  "suspension_ends_at" timestamptz NULL,
  "withdrawn_at" timestamptz NULL,
  "retired_at" timestamptz NULL,
  "supersedes_policy_version_id" uuid NULL,
  "superseded_by_policy_version_id" uuid NULL,
  "precedence_rank" integer NOT NULL DEFAULT 1000,
  "conflict_group_key" character varying(160) NULL,
  "policy_semantic_hash" character varying(80) NOT NULL,
  "policy_semantic_hash_source_version" character varying(80) NOT NULL DEFAULT 'statutory-parking-policy-authority:sha256:v1',
  "reviewed_by_user_id" uuid NULL,
  "reviewed_by" character varying(128) NULL,
  "reviewed_at" timestamptz NULL,
  "approved_by_user_id" uuid NULL,
  "approved_by" character varying(128) NULL,
  "approved_at" timestamptz NULL,
  "correlation_id" uuid NULL,
  "created_at" timestamptz NOT NULL DEFAULT now(),
  "created_by_user_id" uuid NULL,
  "created_by_service_identity_id" uuid NULL,
  "updated_at" timestamptz NOT NULL DEFAULT now(),
  "updated_by_user_id" uuid NULL,
  "updated_by_service_identity_id" uuid NULL,
  "row_version" bigint NOT NULL DEFAULT 1,
  CONSTRAINT "pk_statutory_discount_policy_versions" PRIMARY KEY ("statutory_discount_policy_version_id"),
  CONSTRAINT "uq_sd_policy_versions__code_version" UNIQUE ("policy_code", "policy_version"),
  CONSTRAINT "fk_sd_policy_versions__registry" FOREIGN KEY ("statutory_discount_policy_registry_id") REFERENCES "discounts"."statutory_discount_policy_registry" ("statutory_discount_policy_registry_id"),
  CONSTRAINT "fk_sd_policy_versions__jurisdiction" FOREIGN KEY ("jurisdiction_id") REFERENCES "sites"."jurisdictions" ("jurisdiction_id"),
  CONSTRAINT "fk_sd_policy_versions__local_government_unit" FOREIGN KEY ("local_government_unit_id") REFERENCES "sites"."jurisdictions" ("jurisdiction_id"),
  CONSTRAINT "fk_sd_policy_versions__site_group" FOREIGN KEY ("site_group_id") REFERENCES "sites"."site_groups" ("site_group_id"),
  CONSTRAINT "fk_sd_policy_versions__site" FOREIGN KEY ("site_id") REFERENCES "sites"."sites" ("site_id"),
  CONSTRAINT "fk_sd_policy_versions__supersedes" FOREIGN KEY ("supersedes_policy_version_id") REFERENCES "discounts"."statutory_discount_policy_versions" ("statutory_discount_policy_version_id"),
  CONSTRAINT "fk_sd_policy_versions__superseded_by" FOREIGN KEY ("superseded_by_policy_version_id") REFERENCES "discounts"."statutory_discount_policy_versions" ("statutory_discount_policy_version_id"),
  CONSTRAINT "ck_sd_policy_versions__policy_code_format" CHECK (((policy_code)::text = upper((policy_code)::text) AND ((policy_code)::text ~ '^[A-Z0-9][A-Z0-9_]{2,127}$'::text))),
  CONSTRAINT "ck_sd_policy_versions__jurisdiction_code_format" CHECK (((jurisdiction_code)::text = upper((jurisdiction_code)::text) AND ((jurisdiction_code)::text ~ '^[A-Z]{2}[-_A-Z0-9]{2,63}$'::text))),
  CONSTRAINT "ck_sd_policy_versions__lgu_consistency" CHECK ((local_government_unit_id IS NULL) OR (local_government_unit_id = jurisdiction_id)),
  CONSTRAINT "ck_sd_policy_versions__source_reference_required" CHECK (btrim(source_reference) <> ''::text),
  CONSTRAINT "ck_sd_policy_versions__hash" CHECK ((policy_semantic_hash)::text ~ '^sha256:[0-9a-f]{64}$'::text),
  CONSTRAINT "ck_sd_policy_versions__hash_version" CHECK ((policy_semantic_hash_source_version)::text = 'statutory-parking-policy-authority:sha256:v1'::text),
  CONSTRAINT "ck_sd_policy_versions__scope" CHECK (((policy_scope_type = 'JURISDICTION'::discounts.policy_scope_type_enum AND site_group_id IS NULL AND site_id IS NULL) OR (policy_scope_type = 'SITE_GROUP'::discounts.policy_scope_type_enum AND site_group_id IS NOT NULL AND site_id IS NULL) OR (policy_scope_type = 'SITE'::discounts.policy_scope_type_enum AND site_id IS NOT NULL))),
  CONSTRAINT "ck_sd_policy_versions__local_resolution" CHECK ((policy_level = 'LOCAL_ORDINANCE'::discounts.discount_policy_level_enum) AND (policy_resolution_basis = 'LOCAL_ORDINANCE_APPLIED'::discounts.policy_resolution_basis_enum)),
  CONSTRAINT "ck_sd_policy_versions__transaction_active_verification" CHECK ((transaction_publication_status <> 'ACTIVE_FOR_TRANSACTION_USE'::discounts.statutory_policy_publication_status_enum) OR (source_verification_status = ANY (ARRAY['VERIFIED_OFFICIAL'::discounts.policy_verification_status_enum, 'VERIFIED_ACTIVE_OPERATIONAL'::discounts.policy_verification_status_enum, 'ACTIVE_APPROVED'::discounts.policy_verification_status_enum]))),
  CONSTRAINT "ck_sd_policy_versions__proposed_unverified_not_active" CHECK ((transaction_publication_status <> 'ACTIVE_FOR_TRANSACTION_USE'::discounts.statutory_policy_publication_status_enum) OR (source_verification_status <> ALL (ARRAY['LEAD_UNVERIFIED'::discounts.policy_verification_status_enum, 'VERIFIED_SECONDARY'::discounts.policy_verification_status_enum, 'PROPOSED_ONLY'::discounts.policy_verification_status_enum, 'PROPOSED'::discounts.policy_verification_status_enum, 'NO_LOCAL_RULE_FOUND'::discounts.policy_verification_status_enum, 'STATUS_UNRESOLVED'::discounts.policy_verification_status_enum, 'REJECTED'::discounts.policy_verification_status_enum]))),
  CONSTRAINT "ck_sd_policy_versions__active_parking_covered" CHECK ((transaction_publication_status <> 'ACTIVE_FOR_TRANSACTION_USE'::discounts.statutory_policy_publication_status_enum) OR (parking_service_applicability = 'COVERED'::discounts.parking_service_applicability_status_enum)),
  CONSTRAINT "ck_sd_policy_versions__active_approved" CHECK ((transaction_publication_status <> 'ACTIVE_FOR_TRANSACTION_USE'::discounts.statutory_policy_publication_status_enum) OR (approved_at IS NOT NULL AND (approved_by_user_id IS NOT NULL OR btrim(COALESCE(approved_by, ''::character varying)::text) <> ''::text))),
  CONSTRAINT "ck_sd_policy_versions__transaction_window" CHECK ((transaction_use_effective_to IS NULL) OR (transaction_use_effective_from IS NULL) OR (transaction_use_effective_to > transaction_use_effective_from)),
  CONSTRAINT "ck_sd_policy_versions__legal_window" CHECK ((legal_effective_to IS NULL) OR (legal_effective_from IS NULL) OR (legal_effective_to > legal_effective_from)),
  CONSTRAINT "ck_sd_policy_versions__suspension_window" CHECK ((suspension_ends_at IS NULL) OR (suspension_starts_at IS NULL) OR (suspension_ends_at > suspension_starts_at)),
  CONSTRAINT "ck_sd_policy_versions__suspended_status" CHECK ((transaction_publication_status <> 'SUSPENDED'::discounts.statutory_policy_publication_status_enum) OR (suspension_starts_at IS NOT NULL)),
  CONSTRAINT "ck_sd_policy_versions__withdrawn_status" CHECK ((transaction_publication_status <> 'WITHDRAWN'::discounts.statutory_policy_publication_status_enum) OR (withdrawn_at IS NOT NULL)),
  CONSTRAINT "ck_sd_policy_versions__retired_status" CHECK ((transaction_publication_status <> 'RETIRED'::discounts.statutory_policy_publication_status_enum) OR (retired_at IS NOT NULL)),
  CONSTRAINT "ck_sd_policy_versions__superseded_status" CHECK ((transaction_publication_status <> 'SUPERSEDED'::discounts.statutory_policy_publication_status_enum) OR (superseded_by_policy_version_id IS NOT NULL)),
  CONSTRAINT "ck_sd_policy_versions__no_self_supersession" CHECK ((supersedes_policy_version_id IS NULL OR supersedes_policy_version_id <> statutory_discount_policy_version_id) AND (superseded_by_policy_version_id IS NULL OR superseded_by_policy_version_id <> statutory_discount_policy_version_id)),
  CONSTRAINT "ck_sd_policy_versions__percentage_range" CHECK ((discount_percentage_basis_points IS NULL) OR (discount_percentage_basis_points BETWEEN 0 AND 10000)),
  CONSTRAINT "ck_sd_policy_versions__free_duration_non_negative" CHECK ((free_duration_minutes IS NULL) OR (free_duration_minutes >= 0)),
  CONSTRAINT "ck_sd_policy_versions__cap_non_negative" CHECK ((cap_amount_minor_units IS NULL) OR (cap_amount_minor_units >= 0)),
  CONSTRAINT "ck_sd_policy_versions__cap_currency" CHECK ((cap_amount_minor_units IS NULL) OR (cap_currency_code IS NOT NULL)),
  CONSTRAINT "ck_sd_policy_versions__full_fee_flag" CHECK ((benefit_type <> 'FULL_FEE_EXEMPTION'::discounts.parking_benefit_type_enum) OR (full_fee_exempt IS NULL OR full_fee_exempt = true)),
  CONSTRAINT "ck_sd_policy_versions__unknown_not_zero" CHECK ((free_duration_minutes IS NULL OR free_duration_minutes > 0) AND (cap_amount_minor_units IS NULL OR cap_amount_minor_units > 0)),
  CONSTRAINT "ck_sd_policy_versions__row_version_positive" CHECK (row_version > 0)
);;
