-- Create "statutory_discount_payable_basis_application_commands" table
CREATE TABLE "discounts"."statutory_discount_payable_basis_application_commands" (
  "statutory_discount_payable_basis_application_command_id" uuid NOT NULL DEFAULT gen_random_uuid(),
  "request_reference" uuid NOT NULL,
  "statutory_discount_decision_command_id" uuid NOT NULL,
  "parking_session_id" uuid NOT NULL,
  "site_id" uuid NULL,
  "entitlement_type" character varying(64) NOT NULL,
  "business_identity" character varying(256) NOT NULL,
  "idempotency_scope" character varying(256) NOT NULL,
  "idempotency_key" character varying(128) NOT NULL,
  "semantic_request_hash" character varying(80) NOT NULL,
  "semantic_hash_source_version" character varying(80) NOT NULL,
  "command_status" character varying(64) NOT NULL,
  "result_classification" character varying(64) NOT NULL,
  "retryable" boolean NOT NULL DEFAULT false,
  "recovery_classification" character varying(80) NOT NULL DEFAULT 'NONE',
  "safe_error_code" character varying(128) NULL,
  "statutory_discount_validation_id" uuid NULL,
  "statutory_discount_payable_basis_application_id" uuid NULL,
  "original_tariff_snapshot_id" uuid NULL,
  "target_tariff_snapshot_id" uuid NULL,
  "applied_tariff_snapshot_id" uuid NULL,
  "applied_policy_reference_id" uuid NULL,
  "policy_resolution_basis" character varying(80) NULL,
  "approved_discount_amount_minor_units" bigint NOT NULL,
  "approved_vat_exclusive_amount_minor_units" bigint NULL,
  "approved_vat_amount_minor_units" bigint NULL,
  "approved_final_payable_amount_minor_units" bigint NOT NULL,
  "currency_code" character(3) NOT NULL,
  "source_channel" character varying(64) NOT NULL,
  "original_correlation_id" uuid NOT NULL,
  "created_at" timestamptz NOT NULL DEFAULT now(),
  "processing_started_at" timestamptz NULL,
  "applied_at" timestamptz NULL,
  "completed_at" timestamptz NULL,
  "failed_at" timestamptz NULL,
  "updated_at" timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT "pk_statutory_discount_payable_basis_application_commands" PRIMARY KEY ("statutory_discount_payable_basis_application_command_id"),
  CONSTRAINT "fk_stat_discount_pba_commands__decision_command" FOREIGN KEY ("statutory_discount_decision_command_id") REFERENCES "discounts"."statutory_discount_decision_commands" ("statutory_discount_decision_command_id"),
  CONSTRAINT "fk_stat_discount_pba_commands__parking_session" FOREIGN KEY ("parking_session_id") REFERENCES "core"."parking_sessions" ("parking_session_id"),
  CONSTRAINT "fk_stat_discount_pba_commands__site" FOREIGN KEY ("site_id") REFERENCES "sites"."sites" ("site_id"),
  CONSTRAINT "fk_stat_discount_pba_commands__validation" FOREIGN KEY ("statutory_discount_validation_id") REFERENCES "discounts"."statutory_discount_validations" ("statutory_discount_validation_id"),
  CONSTRAINT "fk_stat_discount_pba_commands__payable_basis_application" FOREIGN KEY ("statutory_discount_payable_basis_application_id") REFERENCES "discounts"."statutory_discount_payable_basis_applications" ("statutory_discount_payable_basis_application_id"),
  CONSTRAINT "fk_stat_discount_pba_commands__original_tariff_snapshot" FOREIGN KEY ("original_tariff_snapshot_id") REFERENCES "core"."tariff_snapshots" ("tariff_snapshot_id"),
  CONSTRAINT "fk_stat_discount_pba_commands__target_tariff_snapshot" FOREIGN KEY ("target_tariff_snapshot_id") REFERENCES "core"."tariff_snapshots" ("tariff_snapshot_id"),
  CONSTRAINT "fk_stat_discount_pba_commands__applied_tariff_snapshot" FOREIGN KEY ("applied_tariff_snapshot_id") REFERENCES "core"."tariff_snapshots" ("tariff_snapshot_id"),
  CONSTRAINT "ck_stat_discount_pba_commands__source_channel" CHECK (source_channel IN ('OPERATOR_CONSOLE', 'WEBPAY', 'ASSISTED_PAYMENT_TERMINAL')),
  CONSTRAINT "ck_stat_discount_pba_commands__entitlement_type" CHECK (entitlement_type IN ('SENIOR_CITIZEN', 'PWD')),
  CONSTRAINT "ck_stat_discount_pba_commands__hash" CHECK (semantic_request_hash ~ '^sha256:[0-9a-f]{64}$'),
  CONSTRAINT "ck_stat_discount_pba_commands__semantic_version" CHECK (semantic_hash_source_version = 'statutory-discount-payable-basis-application:sha256:v1'),
  CONSTRAINT "ck_stat_discount_pba_commands__command_status" CHECK (command_status IN ('RECEIVED', 'PROCESSING', 'APPLIED', 'FAILED_RETRYABLE', 'FAILED_NON_RETRYABLE')),
  CONSTRAINT "ck_stat_discount_pba_commands__result_classification" CHECK (result_classification IN ('APPLIED', 'IDEMPOTENT_REPLAY', 'SEMANTIC_CONFLICT', 'DECISION_NOT_APPROVED', 'DECISION_NOT_FOUND', 'IN_PROGRESS', 'RETRYABLE_FAILURE', 'NON_RETRYABLE_FAILURE')),
  CONSTRAINT "ck_stat_discount_pba_commands__recovery_classification" CHECK (recovery_classification IN ('NONE', 'AWAITING_REVIEW', 'READ_CANONICAL_RESULT', 'RETRY_ORIGINAL_IDEMPOTENCY_KEY', 'WAIT_THEN_RETRY_ORIGINAL_IDEMPOTENCY_KEY', 'CORRECT_REQUEST_REQUIRED', 'NOT_RECOVERABLE')),
  CONSTRAINT "ck_stat_discount_pba_commands__amounts_non_negative" CHECK (approved_discount_amount_minor_units >= 0 AND approved_final_payable_amount_minor_units >= 0 AND (approved_vat_exclusive_amount_minor_units IS NULL OR approved_vat_exclusive_amount_minor_units >= 0) AND (approved_vat_amount_minor_units IS NULL OR approved_vat_amount_minor_units >= 0))
);;
