-- Create "philippine_provinces" table
CREATE TABLE "sites"."philippine_provinces" (
  "philippine_province_id" uuid NOT NULL DEFAULT gen_random_uuid(),
  "philippine_region_id" uuid NOT NULL,
  "psgc_code" character varying(10) NOT NULL,
  "correspondence_code" character varying(16) NULL,
  "province_code" character varying(32) NOT NULL,
  "official_name" character varying(160) NOT NULL,
  "province_status" "sites"."jurisdiction_status_enum" NOT NULL DEFAULT 'ACTIVE',
  "effective_from" timestamptz NOT NULL,
  "effective_to" timestamptz NULL,
  "source_reference" character varying(256) NOT NULL,
  "created_at" timestamptz NOT NULL DEFAULT now(),
  "created_by_user_id" uuid NULL,
  "created_by_service_identity_id" uuid NULL,
  "updated_at" timestamptz NOT NULL DEFAULT now(),
  "updated_by_user_id" uuid NULL,
  "updated_by_service_identity_id" uuid NULL,
  "row_version" bigint NOT NULL DEFAULT 1,
  CONSTRAINT "pk_philippine_provinces" PRIMARY KEY ("philippine_province_id"),
  CONSTRAINT "uq_philippine_provinces__psgc_code" UNIQUE ("psgc_code"),
  CONSTRAINT "uq_philippine_provinces__province_code" UNIQUE ("province_code"),
  CONSTRAINT "fk_philippine_provinces__region" FOREIGN KEY ("philippine_region_id") REFERENCES "sites"."philippine_regions" ("philippine_region_id"),
  CONSTRAINT "ck_philippine_provinces__psgc_code" CHECK ((psgc_code)::text ~ '^[0-9]{10}$'::text),
  CONSTRAINT "ck_philippine_provinces__province_code" CHECK (btrim((province_code)::text) <> ''::text),
  CONSTRAINT "ck_philippine_provinces__official_name" CHECK (btrim((official_name)::text) <> ''::text),
  CONSTRAINT "ck_philippine_provinces__source_reference" CHECK (btrim((source_reference)::text) <> ''::text),
  CONSTRAINT "ck_philippine_provinces__effective_window" CHECK ((effective_to IS NULL) OR (effective_to > effective_from)),
  CONSTRAINT "ck_philippine_provinces__row_version_positive" CHECK (row_version > 0)
);;