-- Create "philippine_regions" table
CREATE TABLE "sites"."philippine_regions" (
  "philippine_region_id" uuid NOT NULL DEFAULT gen_random_uuid(),
  "psgc_code" character varying(10) NOT NULL,
  "correspondence_code" character varying(16) NULL,
  "region_code" character varying(16) NOT NULL,
  "official_name" character varying(160) NOT NULL,
  "short_name" character varying(80) NULL,
  "region_status" "sites"."jurisdiction_status_enum" NOT NULL DEFAULT 'ACTIVE',
  "effective_from" timestamptz NOT NULL,
  "effective_to" timestamptz NULL,
  "source_reference" character varying(256) NOT NULL,
  "created_at" timestamptz NOT NULL DEFAULT now(),
  "created_by_user_id" uuid NULL,
  "created_by_service_identity_id" uuid NULL,
  "updated_at" timestamptz NOT NULL DEFAULT now(),
  "updated_by_user_id" uuid NULL,
  "updated_by_service_identity_id" uuid NULL,
  "row_version" bigint NOT NULL DEFAULT 1,
  CONSTRAINT "pk_philippine_regions" PRIMARY KEY ("philippine_region_id"),
  CONSTRAINT "uq_philippine_regions__psgc_code" UNIQUE ("psgc_code"),
  CONSTRAINT "uq_philippine_regions__region_code" UNIQUE ("region_code"),
  CONSTRAINT "ck_philippine_regions__psgc_code" CHECK ((psgc_code)::text ~ '^[0-9]{10}$'::text),
  CONSTRAINT "ck_philippine_regions__region_code" CHECK (btrim((region_code)::text) <> ''::text),
  CONSTRAINT "ck_philippine_regions__official_name" CHECK (btrim((official_name)::text) <> ''::text),
  CONSTRAINT "ck_philippine_regions__source_reference" CHECK (btrim((source_reference)::text) <> ''::text),
  CONSTRAINT "ck_philippine_regions__effective_window" CHECK ((effective_to IS NULL) OR (effective_to > effective_from)),
  CONSTRAINT "ck_philippine_regions__row_version_positive" CHECK (row_version > 0)
);;