-- Create "jurisdictions" table
CREATE TABLE "sites"."jurisdictions" (
  "jurisdiction_id" uuid NOT NULL DEFAULT gen_random_uuid(),
  "jurisdiction_code" character varying(64) NOT NULL,
  "jurisdiction_type" "sites"."jurisdiction_type_enum" NOT NULL,
  "philippine_region_id" uuid NULL,
  "philippine_province_id" uuid NULL,
  "correspondence_code" character varying(16) NULL,
  "short_display_name" character varying(160) NULL,
  "city_classification" "sites"."city_classification_enum" NULL,
  "display_name" character varying(160) NOT NULL,
  "province_name" character varying(128) NULL,
  "region_name" character varying(128) NULL,
  "country_code" character(2) NOT NULL DEFAULT 'PH',
  "psgc_code" character varying(16) NULL,
  "jurisdiction_status" "sites"."jurisdiction_status_enum" NOT NULL DEFAULT 'ACTIVE',
  "effective_from" timestamptz NULL,
  "effective_to" timestamptz NULL,
  "replaced_by_jurisdiction_id" uuid NULL,
  "source_reference" character varying(256) NULL,
  "source_provenance" text NULL,
  "created_at" timestamptz NOT NULL DEFAULT now(),
  "created_by_user_id" uuid NULL,
  "created_by_service_identity_id" uuid NULL,
  "updated_at" timestamptz NOT NULL DEFAULT now(),
  "updated_by_user_id" uuid NULL,
  "updated_by_service_identity_id" uuid NULL,
  "row_version" bigint NOT NULL DEFAULT 1,
  CONSTRAINT "pk_jurisdictions" PRIMARY KEY ("jurisdiction_id"),
  CONSTRAINT "uq_jurisdictions__code" UNIQUE ("jurisdiction_code"),
  CONSTRAINT "uq_jurisdictions__psgc_code" UNIQUE ("psgc_code"),
  CONSTRAINT "fk_jurisdictions__replaced_by" FOREIGN KEY ("replaced_by_jurisdiction_id") REFERENCES "sites"."jurisdictions" ("jurisdiction_id"),
  CONSTRAINT "fk_jurisdictions__philippine_region" FOREIGN KEY ("philippine_region_id") REFERENCES "sites"."philippine_regions" ("philippine_region_id"),
  CONSTRAINT "fk_jurisdictions__philippine_province" FOREIGN KEY ("philippine_province_id") REFERENCES "sites"."philippine_provinces" ("philippine_province_id"),
  CONSTRAINT "ck_jurisdictions__code_format" CHECK (((jurisdiction_code)::text = upper((jurisdiction_code)::text) AND ((jurisdiction_code)::text ~ '^[A-Z]{2}[-_A-Z0-9]{2,63}$'::text))),
  CONSTRAINT "ck_jurisdictions__display_name" CHECK (btrim((display_name)::text) <> ''::text),
  CONSTRAINT "ck_jurisdictions__country_code" CHECK (country_code = upper(country_code)),
  CONSTRAINT "ck_jurisdictions__psgc_code_format" CHECK ((psgc_code IS NULL) OR ((psgc_code)::text ~ '^[0-9]{10}$'::text)),
  CONSTRAINT "ck_jurisdictions__short_display_name" CHECK ((short_display_name IS NULL) OR (btrim((short_display_name)::text) <> ''::text)),
  CONSTRAINT "ck_jurisdictions__city_classification" CHECK ((jurisdiction_type = 'CITY'::sites.jurisdiction_type_enum) OR (city_classification IS NULL)),
  CONSTRAINT "ck_jurisdictions__effective_window" CHECK ((effective_to IS NULL) OR (effective_from IS NULL) OR (effective_to > effective_from)),
  CONSTRAINT "ck_jurisdictions__no_self_replacement" CHECK ((replaced_by_jurisdiction_id IS NULL) OR (replaced_by_jurisdiction_id <> jurisdiction_id)),
  CONSTRAINT "ck_jurisdictions__row_version_positive" CHECK (row_version > 0)
);;
