-- Create "coupon_applications" table
CREATE TABLE "coupons"."coupon_applications" (
  "coupon_application_id" uuid NOT NULL DEFAULT gen_random_uuid(),
  "coupon_id" uuid NOT NULL,
  "merchant_id" uuid NOT NULL,
  "merchant_wallet_id" uuid NULL,
  "parking_session_id" uuid NOT NULL,
  "tariff_snapshot_id" uuid NULL,
  "payment_attempt_id" uuid NULL,
  "idempotency_key" character varying(128) NOT NULL,
  "application_status" "coupons"."coupon_application_status_enum" NOT NULL,
  "currency_code" character(3) NOT NULL,
  "gross_amount_at_application" numeric(18,2) NOT NULL,
  "coupon_discount_amount" numeric(18,2) NOT NULL,
  "net_amount_after_coupon" numeric(18,2) NOT NULL,
  "reservation_ref" character varying(128) NULL,
  "reserved_at" timestamptz NULL,
  "reservation_expires_at" timestamptz NULL,
  "applied_at" timestamptz NULL,
  "committed_at" timestamptz NULL,
  "released_at" timestamptz NULL,
  "expired_at" timestamptz NULL,
  "rejected_at" timestamptz NULL,
  "cancelled_at" timestamptz NULL,
  "reversed_at" timestamptz NULL,
  "rejection_reason_code" character varying(64) NULL,
  "release_reason_code" character varying(64) NULL,
  "reversal_reason_code" character varying(64) NULL,
  "requested_by_user_id" uuid NULL,
  "requested_by_service_identity_id" uuid NULL,
  "approved_by_user_id" uuid NULL,
  "correlation_id" uuid NULL,
  "created_at" timestamptz NOT NULL DEFAULT now(),
  "created_by_user_id" uuid NULL,
  "created_by_service_identity_id" uuid NULL,
  "updated_at" timestamptz NOT NULL DEFAULT now(),
  "updated_by_user_id" uuid NULL,
  "updated_by_service_identity_id" uuid NULL,
  "row_version" bigint NOT NULL DEFAULT 1,
  CONSTRAINT "pk_coupon_applications" PRIMARY KEY ("coupon_application_id")
);;

