-- Create enum type "operator_action_type_enum"
CREATE TYPE "operations"."operator_action_type_enum" AS ENUM ('SENSITIVE_EVIDENCE_VIEW', 'INCIDENT_ASSIGN', 'INCIDENT_UPDATE', 'RECONCILIATION_REVIEW', 'CONTROLLED_RECHECK', 'PROVIDER_STATUS_QUERY_TRIGGERED', 'SUPPORT_NOTE_ADDED', 'REPORT_EXPORTED', 'CONFIGURATION_VIEW', 'SECURITY_REVIEW');;

