-- Create enum type "override_type_enum"
CREATE TYPE "operations"."override_type_enum" AS ENUM ('MANUAL_GATE_OPEN', 'EXIT_AUTHORIZATION_REISSUE', 'COUPON_EXCEPTION', 'STATUTORY_DISCOUNT_REVIEW_EXCEPTION', 'INCIDENT_RELEASE', 'CONTINUITY_ACTION', 'RECONCILIATION_CORRECTION', 'SUPPORT_ACTION');;

