-- Create enum type "dead_letter_type_enum"
CREATE TYPE "events"."dead_letter_type_enum" AS ENUM ('PUBLICATION_FAILURE', 'BROKER_REJECTION', 'PAYLOAD_VALIDATION_FAILURE', 'ROUTING_FAILURE', 'CONSUMER_FAILURE', 'CONSUMER_REJECTION', 'RETRY_EXHAUSTED', 'UNKNOWN');;

