INSERT INTO config.controlled_code_sets (
    code_set_name,
    code_value,
    code_label,
    code_description,
    code_domain,
    code_status,
    sort_order,
    requires_comment,
    requires_approval,
    is_sensitive,
    effective_from
)
VALUES
('HUMAN_IDENTITY_EVENT_TYPE', 'LOGIN_SUCCEEDED', 'Login Succeeded', 'Human authentication succeeded.', 'IDENTITY', 'ACTIVE', 10, false, false, true, '2026-01-01T00:00:00Z'),
('HUMAN_IDENTITY_EVENT_TYPE', 'LOGIN_FAILED', 'Login Failed', 'Human authentication failed without exposing whether an account exists.', 'IDENTITY', 'ACTIVE', 20, false, false, true, '2026-01-01T00:00:00Z'),
('HUMAN_IDENTITY_EVENT_TYPE', 'ACCOUNT_LOCKED', 'Account Locked', 'Local human authentication was locked under policy.', 'IDENTITY', 'ACTIVE', 30, true, false, true, '2026-01-01T00:00:00Z'),
('HUMAN_IDENTITY_EVENT_TYPE', 'ACCOUNT_UNLOCKED', 'Account Unlocked', 'A governed account lock was removed.', 'IDENTITY', 'ACTIVE', 40, true, true, true, '2026-01-01T00:00:00Z'),
('HUMAN_IDENTITY_EVENT_TYPE', 'LOGOUT_COMPLETED', 'Logout Completed', 'A human session logout completed.', 'IDENTITY', 'ACTIVE', 50, false, false, true, '2026-01-01T00:00:00Z'),
('HUMAN_IDENTITY_EVENT_TYPE', 'SESSION_EXPIRED', 'Session Expired', 'A human session reached a server-owned expiry.', 'IDENTITY', 'ACTIVE', 60, false, false, true, '2026-01-01T00:00:00Z'),
('HUMAN_IDENTITY_EVENT_TYPE', 'SESSION_REVOKED', 'Session Revoked', 'A human session was revoked.', 'IDENTITY', 'ACTIVE', 70, true, true, true, '2026-01-01T00:00:00Z'),
('HUMAN_IDENTITY_EVENT_TYPE', 'CREDENTIAL_CHANGED', 'Credential Changed', 'A local human credential changed.', 'IDENTITY', 'ACTIVE', 80, false, false, true, '2026-01-01T00:00:00Z'),
('HUMAN_IDENTITY_EVENT_TYPE', 'CREDENTIAL_RESET', 'Credential Reset', 'A governed local credential reset completed.', 'IDENTITY', 'ACTIVE', 90, true, true, true, '2026-01-01T00:00:00Z'),
('HUMAN_IDENTITY_EVENT_TYPE', 'ACTIVATION_CHALLENGE_ISSUED', 'Activation Challenge Issued', 'A purpose-bound activation challenge was issued.', 'IDENTITY', 'ACTIVE', 100, false, false, true, '2026-01-01T00:00:00Z'),
('HUMAN_IDENTITY_EVENT_TYPE', 'ACTIVATION_CHALLENGE_CONSUMED', 'Activation Challenge Consumed', 'A purpose-bound activation challenge was consumed.', 'IDENTITY', 'ACTIVE', 110, false, false, true, '2026-01-01T00:00:00Z'),
('HUMAN_IDENTITY_EVENT_TYPE', 'EXTERNAL_IDENTITY_BOUND', 'External Identity Bound', 'An external subject was bound to an ExitPass user.', 'IDENTITY', 'ACTIVE', 120, true, true, true, '2026-01-01T00:00:00Z'),
('HUMAN_IDENTITY_EVENT_TYPE', 'EXTERNAL_IDENTITY_REVOKED', 'External Identity Revoked', 'An external identity binding was revoked.', 'IDENTITY', 'ACTIVE', 130, true, true, true, '2026-01-01T00:00:00Z'),
('HUMAN_IDENTITY_EVENT_TYPE', 'TOTP_ENROLLMENT_STARTED', 'TOTP Enrollment Started', 'A governed TOTP enrollment ceremony started without recording provisioning material.', 'IDENTITY', 'ACTIVE', 140, false, false, true, '2026-01-01T00:00:00Z'),
('HUMAN_IDENTITY_EVENT_TYPE', 'TOTP_CONFIRMED', 'TOTP Confirmed', 'A TOTP authenticator enrollment was confirmed.', 'IDENTITY', 'ACTIVE', 150, false, false, true, '2026-01-01T00:00:00Z'),
('HUMAN_IDENTITY_EVENT_TYPE', 'TOTP_VERIFICATION_SUCCEEDED', 'TOTP Verification Succeeded', 'A TOTP verification succeeded without recording the code.', 'IDENTITY', 'ACTIVE', 160, false, false, true, '2026-01-01T00:00:00Z'),
('HUMAN_IDENTITY_EVENT_TYPE', 'TOTP_VERIFICATION_FAILED', 'TOTP Verification Failed', 'A TOTP verification failed without recording the code.', 'IDENTITY', 'ACTIVE', 170, false, false, true, '2026-01-01T00:00:00Z'),
('HUMAN_IDENTITY_EVENT_TYPE', 'TOTP_THROTTLED', 'TOTP Throttled', 'TOTP verification was throttled under policy.', 'IDENTITY', 'ACTIVE', 180, false, false, true, '2026-01-01T00:00:00Z'),
('HUMAN_IDENTITY_EVENT_TYPE', 'TOTP_RESET', 'TOTP Reset', 'A governed TOTP authenticator reset invalidated prior enrollment.', 'IDENTITY', 'ACTIVE', 190, true, true, true, '2026-01-01T00:00:00Z'),
('HUMAN_IDENTITY_EVENT_TYPE', 'TOTP_REMOVED', 'TOTP Removed', 'A governed TOTP authenticator was removed.', 'IDENTITY', 'ACTIVE', 200, true, true, true, '2026-01-01T00:00:00Z'),
('HUMAN_IDENTITY_EVENT_TYPE', 'ROLE_ASSIGNED', 'Role Assigned', 'A human user-role assignment was activated.', 'IDENTITY', 'ACTIVE', 210, true, true, true, '2026-01-01T00:00:00Z'),
('HUMAN_IDENTITY_EVENT_TYPE', 'ROLE_REVOKED', 'Role Revoked', 'A human user-role assignment was revoked.', 'IDENTITY', 'ACTIVE', 220, true, true, true, '2026-01-01T00:00:00Z'),
('HUMAN_IDENTITY_EVENT_TYPE', 'SITE_SCOPE_GRANTED', 'Site Scope Granted', 'A Site scope was granted to a user-role assignment.', 'IDENTITY', 'ACTIVE', 230, true, true, true, '2026-01-01T00:00:00Z'),
('HUMAN_IDENTITY_EVENT_TYPE', 'SITE_SCOPE_REVOKED', 'Site Scope Revoked', 'A Site scope was revoked from a user-role assignment.', 'IDENTITY', 'ACTIVE', 240, true, true, true, '2026-01-01T00:00:00Z'),
('HUMAN_IDENTITY_EVENT_TYPE', 'SITE_GROUP_SCOPE_GRANTED', 'Site Group Scope Granted', 'A Site Group scope was granted to a user-role assignment.', 'IDENTITY', 'ACTIVE', 250, true, true, true, '2026-01-01T00:00:00Z'),
('HUMAN_IDENTITY_EVENT_TYPE', 'SITE_GROUP_SCOPE_REVOKED', 'Site Group Scope Revoked', 'A Site Group scope was revoked from a user-role assignment.', 'IDENTITY', 'ACTIVE', 260, true, true, true, '2026-01-01T00:00:00Z'),
('HUMAN_IDENTITY_EVENT_TYPE', 'GLOBAL_SCOPE_REQUESTED', 'Global Scope Requested', 'An explicit GLOBAL scope was requested; this event does not grant access.', 'IDENTITY', 'ACTIVE', 270, true, true, true, '2026-01-01T00:00:00Z'),
('HUMAN_IDENTITY_EVENT_TYPE', 'GLOBAL_SCOPE_GRANTED', 'Global Scope Granted', 'An explicit GLOBAL scope was granted under approved policy.', 'IDENTITY', 'ACTIVE', 280, true, true, true, '2026-01-01T00:00:00Z'),
('HUMAN_IDENTITY_EVENT_TYPE', 'GLOBAL_SCOPE_REVOKED', 'Global Scope Revoked', 'An explicit GLOBAL scope was revoked.', 'IDENTITY', 'ACTIVE', 290, true, true, true, '2026-01-01T00:00:00Z'),
('HUMAN_IDENTITY_EVENT_TYPE', 'PRIVILEGED_ACCESS_REQUESTED', 'Privileged Access Requested', 'A privileged role or scope request was submitted.', 'IDENTITY', 'ACTIVE', 300, true, true, true, '2026-01-01T00:00:00Z'),
('HUMAN_IDENTITY_EVENT_TYPE', 'PRIVILEGED_ACCESS_DECIDED', 'Privileged Access Decided', 'An authorized decision was recorded for a privileged access request.', 'IDENTITY', 'ACTIVE', 310, true, true, true, '2026-01-01T00:00:00Z'),
('HUMAN_IDENTITY_EVENT_TYPE', 'AUTHORIZATION_DENIED', 'Authorization Denied', 'A server-side human authorization or scope evaluation denied an operation.', 'IDENTITY', 'ACTIVE', 320, false, false, true, '2026-01-01T00:00:00Z'),
('HUMAN_IDENTITY_EVENT_TYPE', 'SUSPICIOUS_AUTHENTICATION', 'Suspicious Authentication', 'Authentication activity met a controlled suspicious-activity classification.', 'IDENTITY', 'ACTIVE', 330, true, false, true, '2026-01-01T00:00:00Z')
ON CONFLICT ON CONSTRAINT uq_controlled_code_sets__set_value_domain
DO UPDATE SET
    code_label = EXCLUDED.code_label,
    code_description = EXCLUDED.code_description,
    code_status = EXCLUDED.code_status,
    sort_order = EXCLUDED.sort_order,
    requires_comment = EXCLUDED.requires_comment,
    requires_approval = EXCLUDED.requires_approval,
    is_sensitive = EXCLUDED.is_sensitive,
    updated_at = now(),
    row_version = config.controlled_code_sets.row_version + 1;;
