-- Create enum type "coupon_rule_type_enum"
CREATE TYPE "coupons"."coupon_rule_type_enum" AS ENUM ('SITE_GROUP_SCOPE', 'SITE_SCOPE', 'MERCHANT_SCOPE', 'VALIDITY_WINDOW', 'MINIMUM_GROSS_AMOUNT', 'MAXIMUM_DISCOUNT_AMOUNT', 'STACKING_POLICY', 'FULL_WAIVER_ALLOWED', 'WALLET_SUFFICIENCY', 'BASELINE_HOURS_ONLY', 'PAYMENT_RAIL_SCOPE', 'CUSTOM_CONTROLLED');;

