-- ============================================================
-- 02. Enum / Type Definitions
-- Generated from ExitPass v1.2 DDL
-- ============================================================
CREATE TYPE audit.audit_change_type_enum AS ENUM ('CREATE', 'UPDATE', 'DELETE', 'ACTIVATE', 'SUSPEND', 'REVOKE', 'RETIRE', 'APPROVE', 'REJECT', 'CONFIGURE', 'ROTATE_CREDENTIAL_REFERENCE', 'CORRECT', 'MIGRATE');

CREATE TYPE audit.audit_event_category_enum AS ENUM ('DOMAIN_STATE_CHANGE', 'ACCESS', 'CONFIGURATION_CHANGE', 'POLICY_CHANGE', 'SECURITY_RELEVANT', 'INTEGRATION', 'RECONCILIATION', 'MANUAL_OPERATION', 'EVIDENCE_ACCESS', 'EVENTING', 'SYSTEM');

CREATE TYPE audit.audit_event_result_enum AS ENUM ('SUCCESS', 'FAILED', 'DENIED', 'REJECTED', 'EXPIRED', 'CANCELLED', 'DUPLICATE', 'NO_OP', 'UNKNOWN');

CREATE TYPE audit.evidence_access_classification_enum AS ENUM ('INTERNAL', 'RESTRICTED', 'HIGHLY_RESTRICTED');

CREATE TYPE audit.evidence_link_status_enum AS ENUM ('ACTIVE', 'REDACTED', 'PURGED', 'HASH_ONLY', 'REVOKED');

CREATE TYPE audit.evidence_redaction_status_enum AS ENUM ('NOT_REDACTED', 'PARTIALLY_REDACTED', 'FULLY_REDACTED', 'HASH_ONLY');

CREATE TYPE audit.evidence_storage_type_enum AS ENUM ('OBJECT_STORAGE', 'EVIDENCE_VAULT', 'HASH_ONLY', 'EXTERNAL_REFERENCE', 'REDACTED_REFERENCE');

CREATE TYPE audit.evidence_type_enum AS ENUM ('PROVIDER_PAYLOAD', 'PROVIDER_RESPONSE', 'STATUTORY_DISCOUNT_EVIDENCE', 'MANUAL_GATE_EVIDENCE', 'INCIDENT_EVIDENCE', 'RECONCILIATION_EVIDENCE', 'SETTLEMENT_EVIDENCE', 'CONFIGURATION_CHANGE_EVIDENCE', 'SECURITY_EVIDENCE', 'SCREENSHOT', 'DOCUMENT', 'HASH_ONLY_REFERENCE', 'OTHER');

CREATE TYPE audit.security_event_category_enum AS ENUM ('AUTHENTICATION', 'AUTHORIZATION', 'REPLAY', 'RATE_LIMIT', 'WEBHOOK_TRUST', 'TOKEN_VALIDATION', 'EVIDENCE_ACCESS', 'PRIVILEGED_ACCESS', 'CREDENTIAL_REFERENCE', 'SERVICE_IDENTITY', 'SUSPICIOUS_ACTIVITY', 'DATA_ACCESS', 'CONFIGURATION_SECURITY');

CREATE TYPE audit.security_event_result_enum AS ENUM ('ALLOWED', 'DENIED', 'FAILED', 'BLOCKED', 'REJECTED', 'DETECTED', 'ESCALATED', 'UNKNOWN');

CREATE TYPE audit.security_event_status_enum AS ENUM ('OPEN', 'ACKNOWLEDGED', 'UNDER_REVIEW', 'RESOLVED', 'FALSE_POSITIVE', 'ESCALATED', 'CLOSED');

CREATE TYPE audit.security_severity_enum AS ENUM ('LOW', 'MEDIUM', 'HIGH', 'CRITICAL');

CREATE TYPE config.controlled_code_status_enum AS ENUM ('DRAFT', 'ACTIVE', 'SUSPENDED', 'DEPRECATED', 'RETIRED');

CREATE TYPE config.feature_flag_status_enum AS ENUM ('DRAFT', 'ACTIVE', 'SUSPENDED', 'EXPIRED', 'RETIRED');

CREATE TYPE config.rate_limit_enforcement_mode_enum AS ENUM ('MONITOR_ONLY', 'ENFORCE', 'BLOCK', 'CHALLENGE', 'DISABLED');

CREATE TYPE config.rate_limit_policy_status_enum AS ENUM ('DRAFT', 'ACTIVE', 'SUSPENDED', 'RETIRED');

CREATE TYPE config.rate_limit_scope_type_enum AS ENUM ('PUBLIC_LOOKUP', 'PAYMENT_CREATE', 'PROVIDER_CALLBACK', 'GATE_CONSUME', 'ADMIN_API', 'SUPPORT_TOOL', 'EVIDENCE_ACCESS', 'SERVICE_TO_SERVICE', 'MERCHANT_USER', 'DEVICE', 'CUSTOM');

CREATE TYPE config.system_parameter_status_enum AS ENUM ('DRAFT', 'ACTIVE', 'SUSPENDED', 'SUPERSEDED', 'RETIRED');

CREATE TYPE config.system_parameter_type_enum AS ENUM ('TEXT', 'NUMERIC', 'BOOLEAN', 'JSON_REFERENCE');

CREATE TYPE config.ttl_expiry_action_enum AS ENUM ('EXPIRE_RECORD', 'INVALIDATE_RECORD', 'RELEASE_RESERVATION', 'REQUIRE_RECHECK', 'BLOCK_USE', 'PURGE_OR_ARCHIVE', 'NOTIFY_ONLY', 'CUSTOM_WORKFLOW');

CREATE TYPE config.ttl_policy_status_enum AS ENUM ('DRAFT', 'ACTIVE', 'SUSPENDED', 'RETIRED');

CREATE TYPE config.ttl_scope_type_enum AS ENUM ('TARIFF_SNAPSHOT', 'PAYMENT_ATTEMPT', 'PROVIDER_SESSION', 'COUPON_RESERVATION', 'STATUTORY_DISCOUNT_VALIDATION', 'SESSION_LOOKUP_CACHE', 'EXIT_AUTHORIZATION', 'PROVIDER_CALLBACK_REPLAY_WINDOW', 'EVIDENCE_RETENTION', 'OUTBOX_RETRY', 'CUSTOM');

CREATE TYPE core.exit_authorization_status_enum AS ENUM ('ISSUED', 'EXPIRED', 'INVALIDATED');

CREATE TYPE core.parking_session_status_enum AS ENUM ('ACTIVE', 'CLOSED', 'EXPIRED', 'INVALIDATED');

CREATE TYPE core.payment_attempt_status_enum AS ENUM ('REQUESTED', 'PENDING_PROVIDER', 'PENDING_FINALIZATION', 'CONFIRMED', 'FAILED', 'EXPIRED', 'CANCELLED');

CREATE TYPE core.payment_confirmation_status_enum AS ENUM ('RECORDED', 'VOIDED');

CREATE TYPE core.tariff_snapshot_status_enum AS ENUM ('ACTIVE', 'CONSUMED', 'EXPIRED', 'SUPERSEDED', 'INVALIDATED');

CREATE TYPE coupons.coupon_application_status_enum AS ENUM ('REQUESTED', 'RESERVED', 'APPLIED', 'COMMITTED', 'RELEASED', 'EXPIRED', 'REJECTED', 'CANCELLED', 'REVERSED');

CREATE TYPE coupons.coupon_denomination_type_enum AS ENUM ('FIXED_AMOUNT', 'PERCENTAGE', 'FULL_WAIVER');

CREATE TYPE coupons.coupon_rule_evaluation_strategy_enum AS ENUM ('ALL_RULES_MUST_PASS', 'ANY_RULE_MAY_PASS', 'FIRST_MATCH', 'PRIORITY_ORDERED');

CREATE TYPE coupons.coupon_rule_group_status_enum AS ENUM ('DRAFT', 'ACTIVE', 'SUSPENDED', 'RETIRED');

CREATE TYPE coupons.coupon_rule_operator_enum AS ENUM ('EQUALS', 'NOT_EQUALS', 'IN', 'NOT_IN', 'GREATER_THAN', 'GREATER_THAN_OR_EQUAL', 'LESS_THAN', 'LESS_THAN_OR_EQUAL', 'BETWEEN', 'EXISTS', 'NOT_EXISTS');

CREATE TYPE coupons.coupon_rule_status_enum AS ENUM ('DRAFT', 'ACTIVE', 'SUSPENDED', 'RETIRED');

CREATE TYPE coupons.coupon_rule_type_enum AS ENUM ('SITE_GROUP_SCOPE', 'SITE_SCOPE', 'MERCHANT_SCOPE', 'VALIDITY_WINDOW', 'MINIMUM_GROSS_AMOUNT', 'MAXIMUM_DISCOUNT_AMOUNT', 'STACKING_POLICY', 'FULL_WAIVER_ALLOWED', 'WALLET_SUFFICIENCY', 'BASELINE_HOURS_ONLY', 'PAYMENT_RAIL_SCOPE', 'CUSTOM_CONTROLLED');

CREATE TYPE coupons.coupon_stacking_policy_enum AS ENUM ('NO_STACKING', 'STACK_WITH_STATUTORY_DISCOUNT', 'STACK_WITH_COUPON', 'STACK_WITH_BOTH', 'HIGHEST_BENEFIT_ONLY');

CREATE TYPE coupons.coupon_status_enum AS ENUM ('DRAFT', 'ACTIVE', 'SUSPENDED', 'EXPIRED', 'RETIRED');

CREATE TYPE coupons.coupon_type_enum AS ENUM ('STANDARD', 'MERCHANT_SUBSIDY', 'VALIDATION', 'FULL_WAIVER', 'SERVICE_RECOVERY', 'PROMOTIONAL');

CREATE TYPE discounts.discount_evidence_type_enum AS ENUM ('SENIOR_CITIZEN_ID', 'PWD_ID', 'AUTHORIZATION_LETTER', 'SUPPORTING_DOCUMENT', 'VALIDATION_SCREENSHOT', 'HASH_ONLY_REFERENCE', 'OTHER');

CREATE TYPE discounts.discount_policy_level_enum AS ENUM ('NATIONAL_LAW', 'LOCAL_ORDINANCE', 'SITE_POLICY', 'OPERATIONAL_POLICY');

CREATE TYPE discounts.discount_policy_status_enum AS ENUM ('DRAFT', 'ACTIVE', 'SUSPENDED', 'SUPERSEDED', 'RETIRED');

CREATE TYPE discounts.discount_policy_type_enum AS ENUM ('LEGAL_REFERENCE', 'LOCAL_ORDINANCE', 'SITE_POLICY', 'OPERATIONAL_POLICY', 'IMPLEMENTATION_POLICY');

CREATE TYPE discounts.evidence_access_classification_enum AS ENUM ('INTERNAL', 'RESTRICTED', 'HIGHLY_RESTRICTED');

CREATE TYPE discounts.evidence_capture_status_enum AS ENUM ('CAPTURED', 'REFERENCED', 'REDACTED', 'PURGED', 'HASH_ONLY', 'REJECTED');

CREATE TYPE discounts.evidence_redaction_status_enum AS ENUM ('NOT_REDACTED', 'PARTIALLY_REDACTED', 'FULLY_REDACTED', 'HASH_ONLY');

CREATE TYPE discounts.evidence_storage_type_enum AS ENUM ('OBJECT_STORAGE', 'EVIDENCE_VAULT', 'HASH_ONLY', 'EXTERNAL_REFERENCE', 'REDACTED_REFERENCE');

CREATE TYPE discounts.policy_resolution_basis_enum AS ENUM ('LOCAL_ORDINANCE_APPLIED', 'NATIONAL_LAW_FALLBACK', 'SITE_POLICY_OPERATIONAL_ONLY', 'MANUAL_POLICY_SELECTION', 'SYSTEM_DEFAULT');

CREATE TYPE discounts.statutory_discount_validations_channel_enum AS ENUM ('WEB_PAY', 'OPERATOR_ASSISTED', 'SYSTEM_VALIDATED', 'SUPPORT_REVIEW', 'RECONCILIATION_REVIEW');

CREATE TYPE discounts.statutory_discount_validations_status_enum AS ENUM ('REQUESTED', 'PENDING_OPERATOR_REVIEW', 'APPROVED', 'REJECTED', 'FAILED', 'EXPIRED', 'CANCELLED');

CREATE TYPE discounts.statutory_entitlement_type_enum AS ENUM ('SENIOR_CITIZEN', 'PWD', 'OTHER_STATUTORY');

CREATE TYPE events.consumer_checkpoint_status_enum AS ENUM ('ACTIVE', 'LOCKED', 'FAILED', 'PAUSED', 'REPLAYING', 'RESET', 'RETIRED');

CREATE TYPE events.dead_letter_status_enum AS ENUM ('OPEN', 'UNDER_REVIEW', 'REPLAY_REQUESTED', 'REPLAYED', 'RESOLVED', 'REJECTED', 'CLOSED', 'CANCELLED');

CREATE TYPE events.dead_letter_type_enum AS ENUM ('PUBLICATION_FAILURE', 'BROKER_REJECTION', 'PAYLOAD_VALIDATION_FAILURE', 'ROUTING_FAILURE', 'CONSUMER_FAILURE', 'CONSUMER_REJECTION', 'RETRY_EXHAUSTED', 'UNKNOWN');

CREATE TYPE events.domain_event_status_enum AS ENUM ('RECORDED', 'SUPERSEDED', 'CANCELLED', 'IGNORED');

CREATE TYPE events.event_broker_type_enum AS ENUM ('RABBITMQ', 'KAFKA', 'AZURE_SERVICE_BUS', 'AWS_SNS_SQS', 'WEBHOOK', 'IN_PROCESS', 'OTHER');

CREATE TYPE events.event_publication_status_enum AS ENUM ('STARTED', 'PUBLISHED', 'FAILED', 'TIMEOUT', 'REJECTED', 'CANCELLED');

CREATE TYPE events.outbox_publication_status_enum AS ENUM ('PENDING', 'LOCKED', 'PUBLISHED', 'FAILED', 'RETRY_PENDING', 'DEAD_LETTERED', 'CANCELLED');

CREATE TYPE gates.gate_authorization_consumption_status_enum AS ENUM ('REQUESTED', 'VALIDATED', 'CONSUMED', 'DENIED', 'EXPIRED', 'INVALID', 'REPLAYED', 'MISMATCHED', 'FAILED');

CREATE TYPE gates.gate_command_result_status_enum AS ENUM ('NOT_REQUESTED', 'REQUESTED', 'ACKNOWLEDGED', 'OPENED', 'FAILED', 'TIMEOUT', 'UNKNOWN');

CREATE TYPE gates.gate_device_status_enum AS ENUM ('DRAFT', 'ACTIVE', 'MAINTENANCE', 'OFFLINE', 'SUSPENDED', 'RETIRED');

CREATE TYPE gates.gate_device_type_enum AS ENUM ('BARRIER_CONTROLLER', 'LANE_CONTROLLER', 'EXIT_TERMINAL', 'LPR_DEVICE', 'GATEWAY', 'INTEGRATION_ENDPOINT', 'OTHER');

CREATE TYPE gates.gate_event_status_enum AS ENUM ('RECORDED', 'SUCCESS', 'FAILED', 'ERROR', 'ABNORMAL', 'IGNORED', 'DUPLICATE');

CREATE TYPE gates.gate_event_type_enum AS ENUM ('AUTHORIZATION_PRESENTED', 'AUTHORIZATION_VALIDATED', 'AUTHORIZATION_DENIED', 'AUTHORIZATION_CONSUMED', 'GATE_OPEN_COMMAND_REQUESTED', 'GATE_OPEN_ACKNOWLEDGED', 'GATE_OPEN_FAILED', 'BARRIER_RAISED', 'BARRIER_LOWERED', 'VEHICLE_DETECTED', 'VEHICLE_EXITED', 'DEVICE_ONLINE', 'DEVICE_OFFLINE', 'DEVICE_ERROR', 'MANUAL_INTERVENTION', 'TAMPER_ALERT', 'ABNORMAL_EVENT');

CREATE TYPE gates.gate_heartbeat_status_enum AS ENUM ('ONLINE', 'DEGRADED', 'OFFLINE', 'ERROR', 'UNKNOWN');

CREATE TYPE identity.permission_status_enum AS ENUM ('DRAFT', 'ACTIVE', 'DEPRECATED', 'RETIRED');

CREATE TYPE identity.role_permission_binding_status_enum AS ENUM ('ACTIVE', 'SUSPENDED', 'REVOKED', 'EXPIRED', 'RETIRED');

CREATE TYPE identity.role_status_enum AS ENUM ('DRAFT', 'ACTIVE', 'SUSPENDED', 'RETIRED');

CREATE TYPE identity.role_type_enum AS ENUM ('SYSTEM', 'OPERATIONS', 'MERCHANT', 'FINANCE', 'COMPLIANCE', 'SUPPORT', 'SECURITY', 'SERVICE', 'OTHER');

CREATE TYPE identity.service_credential_type_enum AS ENUM ('CLIENT_SECRET_REFERENCE', 'CERTIFICATE_REFERENCE', 'MTLS_CERTIFICATE_REFERENCE', 'API_KEY_REFERENCE', 'JWT_SIGNING_KEY_REFERENCE', 'KEY_VAULT_REFERENCE', 'NONE');

CREATE TYPE identity.service_identity_status_enum AS ENUM ('DRAFT', 'ACTIVE', 'SUSPENDED', 'REVOKED', 'EXPIRED', 'RETIRED');

CREATE TYPE identity.service_identity_type_enum AS ENUM ('INTERNAL_SERVICE', 'EXTERNAL_CLIENT', 'ADAPTER', 'BACKGROUND_WORKER', 'SCHEDULED_JOB', 'WEBHOOK_RECEIVER', 'DEVICE', 'GATEWAY', 'OTHER');

CREATE TYPE identity.user_role_assignment_status_enum AS ENUM ('ACTIVE', 'SUSPENDED', 'REVOKED', 'EXPIRED', 'RETIRED');

CREATE TYPE identity.user_status_enum AS ENUM ('INVITED', 'ACTIVE', 'LOCKED', 'SUSPENDED', 'INACTIVE', 'RETIRED');

CREATE TYPE identity.user_type_enum AS ENUM ('INTERNAL_ADMIN', 'OPERATIONS_USER', 'SITE_OPERATOR', 'SUPPORT_USER', 'FINANCE_USER', 'COMPLIANCE_USER', 'MERCHANT_USER', 'SECURITY_USER', 'OTHER');

CREATE TYPE integration.adapter_mapping_confidence_enum AS ENUM ('MANUAL_APPROVED', 'IMPORTED_APPROVED', 'SYSTEM_DISCOVERED', 'LOW_CONFIDENCE', 'UNKNOWN');

CREATE TYPE integration.adapter_mapping_status_enum AS ENUM ('DRAFT', 'ACTIVE', 'SUSPENDED', 'SUPERSEDED', 'RETIRED');

CREATE TYPE integration.adapter_mapping_type_enum AS ENUM ('SITE_GROUP', 'SITE', 'LANE', 'GATE_DEVICE', 'PAYMENT_RAIL', 'TARIFF_GROUP', 'VENDOR_LOCATION', 'OTHER');

CREATE TYPE integration.http_method_enum AS ENUM ('GET', 'POST', 'PUT', 'PATCH', 'DELETE');

CREATE TYPE integration.integration_credential_status_enum AS ENUM ('DRAFT', 'ACTIVE', 'ROTATION_DUE', 'EXPIRED', 'REVOKED', 'RETIRED');

CREATE TYPE integration.integration_credential_type_enum AS ENUM ('API_KEY_REFERENCE', 'CLIENT_SECRET_REFERENCE', 'OAUTH_CLIENT_REFERENCE', 'MTLS_CERTIFICATE_REFERENCE', 'SIGNING_KEY_REFERENCE', 'WEBHOOK_SECRET_REFERENCE', 'BASIC_AUTH_REFERENCE', 'OTHER');

CREATE TYPE integration.integration_health_check_type_enum AS ENUM ('SCHEDULED_HEALTH_CHECK', 'ON_DEMAND_CHECK', 'REQUEST_FAILURE', 'CALLBACK_FAILURE', 'LATENCY_OBSERVATION', 'RECOVERY_OBSERVATION', 'MANUAL_OBSERVATION');

CREATE TYPE integration.integration_health_status_enum AS ENUM ('AVAILABLE', 'DEGRADED', 'UNAVAILABLE', 'ERROR', 'UNKNOWN');

CREATE TYPE integration.secret_store_type_enum AS ENUM ('KEY_VAULT', 'SECRETS_MANAGER', 'CERTIFICATE_STORE', 'HSM', 'ENVIRONMENT_REFERENCE', 'OTHER');

CREATE TYPE integration.vendor_endpoint_status_enum AS ENUM ('DRAFT', 'ACTIVE', 'MAINTENANCE', 'SUSPENDED', 'DEPRECATED', 'RETIRED');

CREATE TYPE integration.vendor_endpoint_type_enum AS ENUM ('SESSION_LOOKUP', 'TARIFF_QUERY', 'PAYMENT_CREATE', 'PAYMENT_STATUS', 'WEBHOOK_RECEIVE', 'GATE_COMMAND', 'HEALTH_CHECK', 'TOKEN_REQUEST', 'EVIDENCE_UPLOAD', 'OTHER');

CREATE TYPE integration.vendor_system_status_enum AS ENUM ('DRAFT', 'ACTIVE', 'MAINTENANCE', 'SUSPENDED', 'DEPRECATED', 'RETIRED');

CREATE TYPE integration.vendor_system_type_enum AS ENUM ('VENDOR_PMS', 'PAYMENT_PROVIDER', 'GATE_CONTROLLER', 'LPR_PROVIDER', 'MOPS_PROVIDER', 'EVIDENCE_STORAGE', 'NOTIFICATION_PROVIDER', 'OTHER');

CREATE TYPE merchants.merchant_scope_type_enum AS ENUM ('SITE_GROUP', 'SITE');

CREATE TYPE merchants.merchant_site_scope_status_enum AS ENUM ('DRAFT', 'ACTIVE', 'SUSPENDED', 'EXPIRED', 'REVOKED', 'RETIRED');

CREATE TYPE merchants.merchant_status_enum AS ENUM ('DRAFT', 'ACTIVE', 'SUSPENDED', 'INACTIVE', 'RETIRED');

CREATE TYPE merchants.merchant_type_enum AS ENUM ('TENANT', 'ANCHOR_TENANT', 'PROPERTY_OPERATOR', 'INSTITUTION', 'SERVICE_PROVIDER', 'PROMOTIONAL_PARTNER', 'OTHER');

CREATE TYPE merchants.merchant_user_status_enum AS ENUM ('INVITED', 'ACTIVE', 'SUSPENDED', 'REVOKED', 'EXPIRED', 'RETIRED');

CREATE TYPE merchants.merchant_user_type_enum AS ENUM ('MERCHANT_ADMIN', 'MERCHANT_MANAGER', 'MERCHANT_STAFF', 'REPORT_VIEWER', 'COUPON_OPERATOR', 'OTHER');

CREATE TYPE merchants.merchant_wallet_status_enum AS ENUM ('DRAFT', 'ACTIVE', 'SUSPENDED', 'FROZEN', 'CLOSED', 'RETIRED');

CREATE TYPE merchants.merchant_wallet_type_enum AS ENUM ('PRE_FUNDED', 'POSTPAID_SPONSORSHIP', 'CREDIT_LIMIT', 'EXTERNAL_LEDGER', 'PROMOTIONAL_BUDGET', 'OTHER');

CREATE TYPE operations.incident_severity_enum AS ENUM ('LOW', 'MEDIUM', 'HIGH', 'CRITICAL');

CREATE TYPE operations.incident_status_enum AS ENUM ('OPEN', 'ACKNOWLEDGED', 'INVESTIGATING', 'MITIGATED', 'RESOLVED', 'CLOSED', 'CANCELLED');

CREATE TYPE operations.manual_gate_action_status_enum AS ENUM ('RECORDED', 'COMPLETED', 'FAILED', 'CANCELLED', 'UNDER_REVIEW', 'RECONCILED');

CREATE TYPE operations.manual_gate_action_type_enum AS ENUM ('MANUAL_OPEN', 'MANUAL_RELEASE', 'EMERGENCY_OPEN', 'MOPS_RELEASE', 'SUPERVISOR_RELEASE', 'DEVICE_FAILURE_RELEASE', 'INCIDENT_RELEASE');

CREATE TYPE operations.operator_action_status_enum AS ENUM ('RECORDED', 'SUCCESS', 'FAILED', 'DENIED', 'CANCELLED');

CREATE TYPE operations.operator_action_type_enum AS ENUM ('SENSITIVE_EVIDENCE_VIEW', 'INCIDENT_ASSIGN', 'INCIDENT_UPDATE', 'RECONCILIATION_REVIEW', 'CONTROLLED_RECHECK', 'PROVIDER_STATUS_QUERY_TRIGGERED', 'SUPPORT_NOTE_ADDED', 'REPORT_EXPORTED', 'CONFIGURATION_VIEW', 'SECURITY_REVIEW');

CREATE TYPE operations.override_approval_decision_enum AS ENUM ('APPROVED', 'REJECTED', 'ESCALATED', 'CANCELLED', 'EXPIRED');

CREATE TYPE operations.override_request_status_enum AS ENUM ('REQUESTED', 'PENDING_APPROVAL', 'APPROVED', 'REJECTED', 'CANCELLED', 'EXPIRED', 'EXECUTED', 'CLOSED');

CREATE TYPE operations.override_type_enum AS ENUM ('MANUAL_GATE_OPEN', 'EXIT_AUTHORIZATION_REISSUE', 'COUPON_EXCEPTION', 'STATUTORY_DISCOUNT_REVIEW_EXCEPTION', 'INCIDENT_RELEASE', 'CONTINUITY_ACTION', 'RECONCILIATION_CORRECTION', 'SUPPORT_ACTION');

CREATE TYPE payments.central_pms_report_status_enum AS ENUM ('NOT_REPORTED', 'REPORTED', 'ACCEPTED', 'REJECTED', 'FAILED', 'RETRY_PENDING');

CREATE TYPE payments.payment_rail_status_enum AS ENUM ('DRAFT', 'ACTIVE', 'SUSPENDED', 'MAINTENANCE', 'DEPRECATED', 'RETIRED');

CREATE TYPE payments.payment_rail_type_enum AS ENUM ('QRPH', 'CARD', 'EWALLET', 'HOSTED_CHECKOUT', 'BANK_TRANSFER', 'OTHER');

CREATE TYPE payments.provider_callback_processing_status_enum AS ENUM ('RECEIVED', 'PROCESSING', 'PROCESSED', 'DUPLICATE', 'REJECTED', 'FAILED');

CREATE TYPE payments.provider_callback_verification_status_enum AS ENUM ('UNVERIFIED', 'VERIFIED', 'FAILED_SIGNATURE', 'FAILED_TIMESTAMP', 'FAILED_SOURCE', 'FAILED_REPLAY', 'FAILED_SCHEMA', 'UNKNOWN');

CREATE TYPE payments.provider_outcome_status_enum AS ENUM ('CONFIRMED', 'FAILED', 'EXPIRED', 'CANCELLED', 'REJECTED', 'UNKNOWN');

CREATE TYPE payments.provider_session_status_enum AS ENUM ('CREATED', 'ACTIVE', 'PENDING', 'PAID', 'FAILED', 'EXPIRED', 'CANCELLED', 'UNKNOWN');

CREATE TYPE payments.provider_status_query_status_enum AS ENUM ('REQUESTED', 'COMPLETED', 'FAILED', 'TIMEOUT', 'INCONCLUSIVE');

CREATE TYPE reconciliation.mops_transaction_record_status_enum AS ENUM ('RECORDED', 'IMPORTED', 'PENDING_RECONCILIATION', 'RECONCILED', 'DISPUTED', 'REJECTED', 'CANCELLED');

CREATE TYPE reconciliation.reconciliation_comparison_basis_enum AS ENUM ('MOPS_TO_CORE', 'MOPS_TO_SETTLEMENT', 'PROVIDER_TO_CORE', 'MANUAL_GATE_TO_CORE', 'COUPON_WALLET_TO_APPLICATION', 'SETTLEMENT_TO_CONFIRMATION', 'INCIDENT_SCOPE_REVIEW');

CREATE TYPE reconciliation.reconciliation_exception_severity_enum AS ENUM ('LOW', 'MEDIUM', 'HIGH', 'CRITICAL');

CREATE TYPE reconciliation.reconciliation_exception_status_enum AS ENUM ('OPEN', 'ASSIGNED', 'UNDER_REVIEW', 'RESOLVED', 'REJECTED', 'ESCALATED', 'CLOSED', 'CANCELLED');

CREATE TYPE reconciliation.reconciliation_exception_type_enum AS ENUM ('AMOUNT_MISMATCH', 'MISSING_PAYMENT_CONFIRMATION', 'MISSING_PROVIDER_OUTCOME', 'MISSING_MOPS_RECORD', 'DUPLICATE_RECORD', 'MANUAL_GATE_WITHOUT_PAYMENT', 'SETTLEMENT_MISMATCH', 'COUPON_WALLET_MISMATCH', 'UNRESOLVED_CONTINUITY_RECORD', 'POLICY_EXCEPTION', 'UNKNOWN_EXCEPTION');

CREATE TYPE reconciliation.reconciliation_item_status_enum AS ENUM ('PENDING', 'MATCHED', 'MISMATCHED', 'EXCEPTION', 'DISPUTED', 'REJECTED', 'RESOLVED', 'CLOSED');

CREATE TYPE reconciliation.reconciliation_match_status_enum AS ENUM ('NOT_EVALUATED', 'MATCH', 'AMOUNT_MISMATCH', 'MISSING_SOURCE', 'MISSING_TARGET', 'DUPLICATE', 'INCONCLUSIVE', 'REJECTED');

CREATE TYPE reconciliation.reconciliation_run_status_enum AS ENUM ('STARTED', 'PROCESSING', 'COMPLETED', 'FAILED', 'CANCELLED', 'REPROCESSING');

CREATE TYPE reconciliation.reconciliation_run_type_enum AS ENUM ('MOPS_RECONCILIATION', 'PROVIDER_SETTLEMENT', 'MANUAL_GATE_REVIEW', 'INCIDENT_RECONCILIATION', 'COUPON_WALLET_RECONCILIATION', 'PAYMENT_PROVIDER_RECONCILIATION', 'VENDOR_PMS_RECONCILIATION');

CREATE TYPE reconciliation.reconciliation_scope_type_enum AS ENUM ('TIME_WINDOW', 'SITE', 'SITE_GROUP', 'INCIDENT', 'SOURCE_BATCH', 'PAYMENT_RAIL', 'VENDOR_SYSTEM', 'MIXED');

CREATE TYPE reconciliation.settlement_comparison_result_enum AS ENUM ('MATCHED', 'MISMATCHED', 'SHORT_SETTLED', 'OVER_SETTLED', 'MISSING_SETTLEMENT', 'DUPLICATE_SETTLEMENT', 'UNRESOLVED', 'REJECTED');

CREATE TYPE reconciliation.settlement_comparison_source_type_enum AS ENUM ('PROVIDER_SETTLEMENT_REPORT', 'BANK_STATEMENT', 'PAYMENT_RAIL_REPORT', 'MERCHANT_WALLET_LEDGER', 'MOPS_EXPORT', 'MANUAL_COLLECTION_REPORT', 'OTHER');

CREATE TYPE sessions.session_identifier_status_enum AS ENUM ('ACTIVE', 'EXPIRED', 'INVALIDATED', 'SUPERSEDED');

CREATE TYPE sessions.session_lookup_cache_status_enum AS ENUM ('ACTIVE', 'EXPIRED', 'INVALIDATED', 'SUPERSEDED');

CREATE TYPE sessions.session_lookup_type_enum AS ENUM ('PLATE_NUMBER', 'TICKET_NUMBER', 'VENDOR_SESSION_REF', 'QR_REFERENCE', 'COMBINED_PLATE_TICKET');

CREATE TYPE sessions.session_resolution_channel_enum AS ENUM ('WEB_PAY', 'OPERATOR_ASSISTED', 'INTERNAL_SERVICE', 'RECONCILIATION_RECHECK', 'SUPPORT_RECHECK');

CREATE TYPE sessions.session_resolution_request_status_enum AS ENUM ('REQUESTED', 'PROCESSING', 'COMPLETED', 'FAILED', 'EXPIRED', 'CANCELLED');

CREATE TYPE sessions.session_resolution_result_status_enum AS ENUM ('RESOLVED_SINGLE', 'NOT_FOUND', 'AMBIGUOUS', 'FAILED', 'EXPIRED', 'CANCELLED');

CREATE TYPE sites.device_assignment_status_enum AS ENUM ('ACTIVE', 'SUSPENDED', 'SUPERSEDED', 'EXPIRED', 'RETIRED');

CREATE TYPE sites.device_assignment_type_enum AS ENUM ('GATE_DEVICE', 'LPR_DEVICE', 'LANE_CONTROLLER', 'PAYMENT_DEVICE', 'SERVICE_PRINCIPAL', 'OTHER');

CREATE TYPE sites.lane_direction_enum AS ENUM ('INBOUND', 'OUTBOUND', 'BIDIRECTIONAL', 'NOT_APPLICABLE');

CREATE TYPE sites.lane_status_enum AS ENUM ('DRAFT', 'ACTIVE', 'MAINTENANCE', 'SUSPENDED', 'INACTIVE', 'RETIRED');

CREATE TYPE sites.lane_type_enum AS ENUM ('ENTRY', 'EXIT', 'MIXED', 'VALIDATION', 'SERVICE', 'OTHER');

CREATE TYPE sites.site_group_status_enum AS ENUM ('DRAFT', 'ACTIVE', 'SUSPENDED', 'INACTIVE', 'RETIRED');

CREATE TYPE sites.site_status_enum AS ENUM ('DRAFT', 'ACTIVE', 'SUSPENDED', 'INACTIVE', 'RETIRED');

CREATE TYPE sites.site_type_enum AS ENUM ('OPEN_LOT', 'STRUCTURED_PARKING', 'MALL_PARKING', 'MIXED_USE_PROPERTY', 'TERMINAL', 'CAMPUS', 'OTHER');

