-- Create enum type "audit_event_category_enum"
CREATE TYPE "audit"."audit_event_category_enum" AS ENUM ('DOMAIN_STATE_CHANGE', 'ACCESS', 'CONFIGURATION_CHANGE', 'POLICY_CHANGE', 'SECURITY_RELEVANT', 'INTEGRATION', 'RECONCILIATION', 'MANUAL_OPERATION', 'EVIDENCE_ACCESS', 'EVENTING', 'SYSTEM');;

