-- Create enum type "security_event_category_enum"
CREATE TYPE "audit"."security_event_category_enum" AS ENUM ('AUTHENTICATION', 'AUTHORIZATION', 'REPLAY', 'RATE_LIMIT', 'WEBHOOK_TRUST', 'TOKEN_VALIDATION', 'EVIDENCE_ACCESS', 'PRIVILEGED_ACCESS', 'CREDENTIAL_REFERENCE', 'SERVICE_IDENTITY', 'SUSPICIOUS_ACTIVITY', 'DATA_ACCESS', 'CONFIGURATION_SECURITY');;

