-- Create enum type "evidence_type_enum"
CREATE TYPE "audit"."evidence_type_enum" AS ENUM ('PROVIDER_PAYLOAD', 'PROVIDER_RESPONSE', 'STATUTORY_DISCOUNT_EVIDENCE', 'MANUAL_GATE_EVIDENCE', 'INCIDENT_EVIDENCE', 'RECONCILIATION_EVIDENCE', 'SETTLEMENT_EVIDENCE', 'CONFIGURATION_CHANGE_EVIDENCE', 'SECURITY_EVIDENCE', 'SCREENSHOT', 'DOCUMENT', 'HASH_ONLY_REFERENCE', 'OTHER');;

