-- Create enum type "gate_event_type_enum"
CREATE TYPE "gates"."gate_event_type_enum" AS ENUM ('AUTHORIZATION_PRESENTED', 'AUTHORIZATION_VALIDATED', 'AUTHORIZATION_DENIED', 'AUTHORIZATION_CONSUMED', 'GATE_OPEN_COMMAND_REQUESTED', 'GATE_OPEN_ACKNOWLEDGED', 'GATE_OPEN_FAILED', 'BARRIER_RAISED', 'BARRIER_LOWERED', 'VEHICLE_DETECTED', 'VEHICLE_EXITED', 'DEVICE_ONLINE', 'DEVICE_OFFLINE', 'DEVICE_ERROR', 'MANUAL_INTERVENTION', 'TAMPER_ALERT', 'ABNORMAL_EVENT');;

