-- Create "incident_records" table
CREATE TABLE "operations"."incident_records" (
  "incident_record_id" uuid NOT NULL DEFAULT gen_random_uuid(),
  "incident_code" character varying(64) NOT NULL,
  "incident_title" character varying(256) NOT NULL,
  "incident_description" text NULL,
  "incident_category" character varying(64) NOT NULL,
  "incident_severity" "operations"."incident_severity_enum" NOT NULL,
  "incident_status" "operations"."incident_status_enum" NOT NULL,
  "site_group_id" uuid NULL,
  "site_id" uuid NULL,
  "lane_id" uuid NULL,
  "gate_device_id" uuid NULL,
  "vendor_system_id" uuid NULL,
  "payment_rail_id" uuid NULL,
  "started_at" timestamptz NOT NULL DEFAULT now(),
  "detected_at" timestamptz NOT NULL,
  "resolved_at" timestamptz NULL,
  "closed_at" timestamptz NULL,
  "closure_reason_code" character varying(64) NULL,
  "owner_user_id" uuid NULL,
  "owner_service_identity_id" uuid NULL,
  "requires_reconciliation" boolean NOT NULL DEFAULT false,
  "requires_post_incident_review" boolean NOT NULL DEFAULT false,
  "correlation_id" uuid NULL,
  "created_at" timestamptz NOT NULL DEFAULT now(),
  "created_by_user_id" uuid NULL,
  "created_by_service_identity_id" uuid NULL,
  "updated_at" timestamptz NOT NULL DEFAULT now(),
  "updated_by_user_id" uuid NULL,
  "updated_by_service_identity_id" uuid NULL,
  "row_version" bigint NOT NULL DEFAULT 1,
  CONSTRAINT "pk_incident_records" PRIMARY KEY ("incident_record_id")
);;

